### ISSUE TITLE
Universal Control OSX 12.3/iOS 15.4 not working

### ISSUE THREAD

**Issue by d34vbd5** [linearmouse/linearmouse#110]
Linearmouse seems to block the new OSX 12.3 / iOS 15.4 Universal Control Feature.
When Linearmouse is running you cant move the mouse out of the screen its stuck at the border.

**Comment by lujjjh** [comment]
Please see [this comment](https://github.com/linearmouse/linearmouse/issues/106#issuecomment-1056118059).
