### ISSUE TITLE
[Feature Request] Per-app settings

### ISSUE THREAD

**Issue by Endy3032** [linearmouse/linearmouse#111]
Hi there! I feel like it'd be great if it also provides per-app settings, or even apple script definitions to programmatically edit the settings on the fly. Still, this is a great app! Thanks :D

**Comment by Nyunyun** [comment]
I concur, side buttons work normally on some apps (without universal back), but stop working with universal back enabled.
e.g. Telegram Lite

**Comment by lujjjh** [comment]
> I concur, side buttons work normally on some apps (without universal back), but stop working with universal back enabled. e.g. Telegram Lite

This is related with #57.

LinearMouse's current solution is to keep [a list of apps](https://github.com/linearmouse/linearmouse/blob/7d0bd90cae403912f93658f2de55633c395ea284/LinearMouse/Event/UniversalBackForward.swift#L25-L32) for which the universal back and forward feature should be disabled.

However, based on my observations, it appears that quite third-party apps do not support swipe gestures but do respond to side buttons. Perhaps we should do the opposite and keep a list of apps for which the feature should be enabled?

Can anyone find examples of third-party apps that only support swipe gestures but do not respond to side buttons?

**Comment by aramann** [comment]
> Can anyone find examples of third-party apps that only support swipe gestures but do not respond to side buttons?

It would be great to add games like dota, cs:go to ignore list, because side buttons are often used for game buttons

**Comment by lujjjh** [comment]
@aramann That makes sense! It's weird that CS doesn't have a bundle id...

Would you like to send a pull request to add `com.valvesoftware.dota2` into the [`ignoreSet`](https://github.com/linearmouse/linearmouse/edit/main/LinearMouse/Event/UniversalBackForward.swift)?

**Comment by lujjjh** [comment]
@aramann

> hope I made it right 

Looks pretty good!

> `com.valvesoftware.steam` isn't working for cs. It runs with a unix file and doesn't have .app

You are right. I just saw the log and the bundle id was `(nil)`.

I'll merge your pull request first.

**Comment by lujjjh** [comment]
Closing this issue since per-app settings can now be configured through configuration.
