### ISSUE TITLE
After user switching the settings are not re-applied

### ISSUE THREAD

**Issue by romaninsh** [linearmouse/linearmouse#112]
I use multiple users on my mac. I use setting 1950 on all accounts. When i switch between users, sometimes mouse settings are oversensitive until i open the Preferences, set sensitivity to 1951 and then back to 1950, then the mouse is working OK again.

That problem is only on one of my accounts. Perhaps the preferences could be force-applied after user is switched into the account.

Thanks!

p.s. thanks for amazing software, have a coffee on me!

**Comment by lujjjh** [comment]
Thank you for your feedback! And coffee :)

I haven't thought about the multi-user scenario. After consideration, it appears more reasonable to run LinearMouse separately for each user, and LinearMouse only affects the user on which it runs.

I'll try to fix this issue in the next minor release.

**Comment by lujjjh** [comment]
[v0.6.0-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.6.0-beta.2) is now available. You can upgrade to that version by checking the “Include beta” box in Preferences → General.

After upgrading to v0.6.0-beta.2, you can run LinearMouse in each of your accounts independently. LinearMouse will only affect the account on which it runs.
