### ISSUE TITLE
Modifier Key for toggling cursor acceleration / sensitivity?

### ISSUE THREAD

**Issue by LBYPatrick** [linearmouse/linearmouse#114]
It would be nice if we have this feature since I switch between my trackpad and mouse quite frequently. 

> It would be even better if we can implement event-based profile switching. That is, whenever we plug in our mouse, we perform certain actions specified by the user and notify the user via notification regarding the switch(es).

**Comment by lujjjh** [comment]
Will be tracked in #144.

**Comment by lujjjh** [comment]
Implemented in [v0.7.0](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.0).
