### ISSUE TITLE
Side key to swipe window? 

### ISSUE THREAD

**Issue by WangQiang102938** [linearmouse/linearmouse#119]
Want a option to use side key as 3-finger swipe gesture/control + left(right)arrow.
If possible, add more feature about side key (like open mission control, etc.)
thanks.
---
希望大佬能让鼠标侧键有切换桌面的选项。代替control+左右方向键。
前进返回用的少，但是切桌面是真的多啊。
还有如果可能的话，给侧键加点其他手势，比如长按侧键开启mission control之类的。
望采纳。

**Comment by lujjjh** [comment]
I'm closing this issue since [this has been implemented](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#switch-spaces-desktops-with-the-command--back-and-command--forward). Please feel free to reopen it if you have any further questions.
