### ISSUE TITLE
mouse conflict with Karabiner-Elements

### ISSUE THREAD

**Issue by ghtjason** [linearmouse/linearmouse#120]
With LinearMouse running, selecting the same mouse as a modified device under the "Devices" tab in Karabiner-Elements leads to strange mouse behavior, even with no mouse keys/buttons actually rebound in Karabiner. Moving the mouse too fast with both enabled makes mouse movement reverse for a short period, causing the cursor to almost loop on screen when moving the physical mouse in a single direction.

Running only LinearMouse or only Karabiner-Elements allows each program to function correctly; however, I'm currently trying to disable mouse acceleration in LinearMouse while simultaneously rebinding the side mouth buttons to a different input with Karabiner. Any help would be appreciated!

macOS 12.3.1, LinearMouse 0.5.4, Karabiner-Elements 14.4.0

**Comment by lujjjh** [comment]
Thank you for your feedback!

I'm unable to reproduce it. Is there anything I'm missing?

https://user-images.githubusercontent.com/3000535/166859429-efc8a12e-950b-4d38-b7fa-f223bb4128e2.mov

**Comment by ghtjason** [comment]
Weird. I've attached a video here, and verified that the same thing happens even with another mouse (Logitech M510). Slowly moving the mouse still works as intended, the issue only arises when flicking across the screen.
https://user-images.githubusercontent.com/20862981/167224717-d1797376-66db-461c-b70b-c7f24bb295bb.mp4

**Comment by ghtjason** [comment]
Did a bit more testing and found that the issue still persisted even without LinearMouse, just to a less noticeable extent due to how high my sensitivity is without LinearMouse running. Seems like this is just an issue with certain mice and Karabiner-Elements on Monterey.

Apologies for blaming LinearMouse here; seems like it's working as intended! Thanks for this amazing piece of free software! :)

**Comment by lujjjh** [comment]
No need to apologize at all. :) Your troubleshooting is helpful to others as well. Thanks for sharing!
