### ISSUE TITLE
Mouse Acceleration

### ISSUE THREAD

**Issue by AdrianTheFrog** [linearmouse/linearmouse#150]
(help wanted) Even with the acceleration slider set to 0 cursor acceleration is still there

**Comment by lujjjh** [comment]
Hey, @LegoAdrian!

Thank you for your feedback!

A few questions to help me in determining what's going on:

1. When you adjust the acceleration slider, does the acceleration change?
2. Does “Disable acceleration & sensitivity” work for you?

Also, would you like to [attach the logs](https://github.com/linearmouse/linearmouse/discussions/117) when you adjust the acceleration?

**Comment by LegoAdrian** [comment]
Here is the log when I started the program and adjusted the mouse settings, it is very long
[linearmouse logs.txt](https://github.com/linearmouse/linearmouse/files/9031829/linearmouse.logs.txt)

**Comment by lujjjh** [comment]
It seems that the only pointing device detected by LinearMouse is the internal trackpad.

That's weird. What kind of mouse are you using?

**Comment by LegoAdrian** [comment]
I was using the internal trackpad, but the GitHub page says it supports trackpads. Is that wrong?

**Comment by lujjjh** [comment]
> I was using the internal trackpad, but the GitHub page says it supports trackpads. Is that wrong?

Trackpads (or per-device settings) are not supported before v0.7.0. It seems that you were using v0.6.x from the log.

If you want to adjust the internal trackpad, maybe you would like to try the latest version.
