### ISSUE TITLE
External trackpads connected via bluetooth does not work

### ISSUE THREAD

**Issue by lxx909546478** [linearmouse/linearmouse#170]
I set the internal trackpad to not use linear scroll. And set outer mouse and trackpad to use linear scroll.
But I find a bug.
When I switch from the internal trackpad to the outer trackpad, the outer trackpad doesn't use linear scroll.
When I switch from the mouse to the outer trackpad, the outer trackpad uses linear scroll.
I'm not sure if it can be reproduced on your device.
Thank you for your attention!

**Comment by lujjjh** [comment]
Thank you for your feedback!

I assume that you are reporting a bug in v0.7.0-beta.x.

Could you please verify if the active device has changed when you switch to the external trackpad?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/3000535/176979126-06d43ef5-10b9-4e73-aae1-43c632ab97f2.png">

**Comment by lxx909546478** [comment]
> Thank you for your feedback!
> 
> I assume that you are reporting a bug in v0.7.0-beta.x.
> 
> Could you please verify if the active device has changed when you switch to the external trackpad?
> 
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/3000535/176979126-06d43ef5-10b9-4e73-aae1-43c632ab97f2.png">

Thank you for your reply!
Yes, the version is v0.7.0-beta.2. 
I notice that when I use the external trackpad connected with bluetooth, the active device doesn't change.
But when I use the external trackpad connected with wire, the active trackpad can be recognized.
This screenshot was recorded when using the external trackpad connected with bluetooth.
<img width="886" alt="iShot_2022-07-02_08 44 37" src="https://user-images.githubusercontent.com/48379537/176980680-db11b798-4386-4c61-9269-636721bb64b2.png">

**Comment by lujjjh** [comment]
Thank you for the detailed information.

I believe this is a bug. I will see if I can reproduce and fix it without an external trackpad.

**Comment by lujjjh** [comment]
妙控板看起来有些特殊，我试图在[这个版本](https://github.com/linearmouse/linearmouse/actions/runs/2601564656)里兼容了妙控板。但是由于身边没有妙控板，可否帮忙测试一下？

由于实现与普通设备不同，预期的行为是，切换到妙控板后不会立即切换为“活跃”，而是在双指滑动后才会切换为“活跃”。这个行为会影响配置时“自动切换到活跃设备”的体验，但是应当能修复你遇到的问题。

> **Note**
>
> 1. 由于这个版本没有正式发布，打开时可能需要右键、打开来绕过 GateKeeper；
> 2. 测试完毕后请替换回正式版本或者已发布的 beta 版本，避免影响 app 更新。

谢谢！

**Comment by lxx909546478** [comment]
> 妙控板看起来有些特殊，我试图在[这个版本](https://github.com/linearmouse/linearmouse/actions/runs/2601564656)里兼容了妙控板。但是由于身边没有妙控板，可否帮忙测试一下？
> 
> 由于实现与普通设备不同，预期的行为是，切换到妙控板后不会立即切换为“活跃”，而是在双指滑动后才会切换为“活跃”。这个行为会影响配置时“自动切换到活跃设备”的体验，但是应当能修复你遇到的问题。
> 
> > Note
> > 
> > 1. 由于这个版本没有正式发布，打开时可能需要右键、打开来绕过 GateKeeper；
> > 2. 测试完毕后请替换回正式版本或者已发布的 beta 版本，避免影响 app 更新。
> 
> 谢谢！

是的，这个版本的程序正如您描述的那样工作，蓝牙连接的妙控板在双指滑动后会切换到“活跃”，我之前描述的问题得到了解决。
再次感谢您的帮助！
