### ISSUE TITLE
With dark mode enabled, scroll bar in Release Notes is white

### ISSUE THREAD

**Issue by rakleed** [linearmouse/linearmouse#186]
With the dark mode enabled, the scroll bar in Release Notes in Auto Updater window is white.

<details><summary>Screenshot</summary>

<img width="720" alt="Screenshot 2022-07-04 at 00 53 04" src="https://user-images.githubusercontent.com/19418601/177059767-61c93c5e-3ed6-4195-9053-79817856c158.png">

</details>

Are you using the latest version of Sparkle?

**Comment by lujjjh** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/3000535/177072732-e6821b11-c663-46b6-9df9-b3e6a4b78742.png">

Although I'm using a fork of Sparkle 2.0, I can reproduce it with [the latest official version](https://github.com/sparkle-project/Sparkle/releases/tag/2.2.0).

I'll look into it.
