### ISSUE TITLE
Trackpad scrolling inertia no longer works

### ISSUE THREAD

**Issue by davidrobertson** [linearmouse/linearmouse#190]
Hi, love the app, thanks.  The only issue I've seen so far is that trackpad scrolling inertia is disabled when the app is running.  Closing the app restores trackpad scrolling inertia.

**Comment by lujjjh** [comment]
Hi, @davidrobertson!

Have you checked the scrolling settings for trackpad? It sounds like linear scrolling has been enabled for trackpad.

<img width="962" alt="Screen Shot" src="https://user-images.githubusercontent.com/3000535/177674141-0ad7549b-ce5a-4a4d-8450-4e0338b12c11.png">

If that's not the case, it would be helpful if you attach your configuration file. You can find it by clicking Config → Reveal in Finder:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3000535/177674624-80072e22-7d91-4bcc-b190-5f9f9bea2ba3.png">

**Comment by davidrobertson** [comment]
Yes I've messed with that setting, disabling it (unchecking) also disables inertia.

The default trackpad scrolling behavior is what's wanted, not linear (by line / pixel).

The contents of my linearmouse.json file are:
`{
  "$schema" : "https:\/\/app.linearmouse.org\/schema\/0.7.1-beta.1",
  "schemes" : [
    {
      "buttons" : {
        "universalBackForward" : true
      },
      "if" : {
        "device" : {
          "productName" : "USB Receiver",
          "productID" : "0xc539",
          "category" : "mouse",
          "vendorID" : "0x46d"
        }
      },
      "pointer" : {
        "acceleration" : 0,
        "speed" : 0.4,
        "disableAcceleration" : false
      },
      "scrolling" : {
        "reverse" : {
          "horizontal" : false,
          "vertical" : true
        },
        "distance" : 3
      }
    },
    {
      "buttons" : {
        "universalBackForward" : true
      },
      "if" : {
        "device" : {
          "productName" : "Apple Internal Keyboard \/ Trackpad",
          "productID" : "0x342",
          "category" : "trackpad",
          "vendorID" : "0x5ac"
        }
      },
      "pointer" : {
        "acceleration" : 0.875,
        "speed" : 0.0689655172413792768,
        "disableAcceleration" : false
      },
      "scrolling" : {
        "distance" : "auto"
      }
    }
  ]
}`

**Comment by lujjjh** [comment]
Glad you got it fixed! Linear scrolling disables scrolling inertia by design.

Feel free to reopen this issue if you have further questions :)

**Comment by lujjjh** [comment]
I've reproduced it, will fix it soon.

For the moment, you may manually remove

```
"distance": "auto",
```

and reload the configuration.

**Comment by davidrobertson** [comment]
That did it, you're a hero!  Thanks!
