### ISSUE TITLE
Program doesn't activate on startup

### ISSUE THREAD

**Issue by krishpa2** [linearmouse/linearmouse#191]
LinearMouse does not activate when the computer starts, and I have to manually recheck my settings.

**Comment by lujjjh** [comment]
Thank you for your feedback!

What does "not activate" mean exactly? Not launched (without an icon shown in the menu) or launched but settings not applied?

And do you mean that the settings have been lost after the restart when you say "manually recheck my settings"?

**Comment by krishpa2** [comment]
Sorry for wasting your time. I realized this only happened when I plugged in my external mouse, so I had to put in new settings.

**Comment by lujjjh** [comment]
Not at all. Anything about LinearMouse that is confusing would be great to hear.

Each mouse should only require a single configuration, and LinearMouse will then automatically apply the settings even if the mouse is re-plugged.

However, it is not very convenient for users who switch mice oftenly, so I'll think about integrating the ability to configure "all mice" into the UI.
