### ISSUE TITLE
Failed to save the configuration: You don’t have permission to save the file “linearmouse” in the folder “.config”.

### ISSUE THREAD

**Issue by Powerofthesun** [linearmouse/linearmouse#197]
After update, this does not go away. I've uninstalled and reinstalled several times

**Comment by lujjjh** [comment]
Hi, @Powerofthesun!

Thank you for reporting this.

Could you please check the ownership and permission of your `~/.config` folder? LinearMouse stores its configuration in that folder.

```sh
$ ls -ld ~/.config 
drwxr-xr-x  6 jiahao  staff  192 Jul  3 12:36 /Users/jiahao/.config
```

**Comment by lujjjh** [comment]
Update: Please refer to https://github.com/linearmouse/linearmouse/issues/230#issuecomment-1207143043
