### ISSUE TITLE
The latest update broke scrolling inertia on trackpads & magic mouse

### ISSUE THREAD

**Issue by abby2k1** [linearmouse/linearmouse#198]
before the latest update, releasing your fingers from the trackpad while scrolling would cause the page to keep moving for a little bit before coming to a stop (same behavior as on ios), but now it doesn't and that makes scrolling slower and really weird feeling with that sudden stop as soon as you lift your fingers.

**Comment by abby2k1** [comment]
I'm sorry I didn't see that this issue had already been posted, closed, and addressed with a beta update. My bad 🤦‍♀️

**Comment by lujjjh** [comment]
It appears that this problem is pretty common. I'll soon release v0.7.1.
