### ISSUE TITLE
Delay before initialization after connecting mouse

### ISSUE THREAD

**Issue by dryk** [linearmouse/linearmouse#209]
When using linearmouse prior to recent updates, its settings seemed to activate immediately upon connecting my magic mouse to my MacBook Pro. After recent updates, however, there appears to be a delay of about 15-20 seconds before linearmouse adjusts my tracking speed and reduces pointer acceleration upon connecting my mouse.

One additional variable, however, is that I recently upgraded from an Intel to Apple silicon mac.

**Comment by lujjjh** [comment]
Could you please check if your Magic Mouse is shown in the device list immediately upon connected?

<img width="962" src="https://user-images.githubusercontent.com/3000535/179644920-a4167f18-45e0-4aaf-a7ee-ad1d230fe826.png">

**Comment by lujjjh** [comment]
Could you please attach the logs (#117) from the time you connect the magic mouse to the time the pointer settings are applied? That will be greatly helpful.

Thank you very much!

**Comment by lujjjh** [comment]
Although I cannot reproduce this issue, I'm guessing there is some race conditions causing the pointer settings not being applied when the device is connected.

Would you like to try [this build](https://github.com/linearmouse/linearmouse/actions/runs/2699134917)?

**Comment by Farianit** [comment]
I have the same issue with Magic Mouse, tracking speed and pointer acceleration settings are not applied when I connect it. But it applies just as I open linearmouse preferences window.

My logs when I connect my Magic Mouse:
`error	02:34:38.089082+0300	LinearMouse	Unable to serialize CFObject: Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')`

LinearMouse 0.7.3
MacOS 12.5.1
Apple M1

**Comment by lujjjh** [comment]
Fixed in [v0.7.6-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.6-beta.1).
