### ISSUE TITLE
Linear Scroll Fixes mouse, but breaks trackpad

### ISSUE THREAD

**Issue by GrumpyChunks** [linearmouse/linearmouse#210]
Having just reinstalled my Mid-2015 Retina MacBook Pro and having previously heard about LinearMouse, I thought I'd give it a try instead of my usual solution, SteerMouse.

Background: The scroll wheel response on my Logitech mouse is awful (it goes from a couple of pixels at a time, to a full page at time, with no inbetween), and it's quite frustrating to use.

What I have found with LinearMouse though, is that whilst it perfectly cures my mouse wheel acceleration, it breaks two finger scrolling on my trackpad, as slowly dragging two fingers over the trackpad, causes the page to scroll insanely fast, but the faster I drag two fingers over the trackpad, the slower it scrolls, which makes it very difficult to control for normal speed scrolling with the trackpad.

If I quit LinearMouse, my trackpad works as it should, but then obviously my mousewheel becomes unusable again.

I've also tried tweaking settings for the mouse in the setting app, under Mouse, Trackpad, and the 'Pointer Control' options under the accessibility section, but haven't been able to find a useable compromise.

I've not found a way of separately configuring the mouse wheel and trackpad, but wondering if this could be a feature for a later release, as I'd like to have the trackpad respond natively, but only modify mouse scroll wheel response.

Edit: I'm running MacOS Monterey 12.4, with no other third party mouse drivers/software. If this is related to [this](https://github.com/linearmouse/linearmouse/issues/17) issue. If so, apologies, please close this issue.

**Comment by lujjjh** [comment]
Could you please check if the active device in the LinearMouse Preferences is switched to trackpad when you drag two fingers over trackpad?

<img width="962" src="https://user-images.githubusercontent.com/3000535/179646517-2786c634-6bec-4940-84eb-996416d32310.png">

And it would be helpful if the configuration file is attached. You may find it by clicking Config → Reveal in Finder:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/3000535/179646702-4b1fb07a-35e5-40ad-bb1b-858f98820ede.png">

**Comment by Stooovie** [comment]
Where is this dialog (active device)? I'm on 0.7.2 and I don't see it. 

The same issue happens with Wacom tablets - pan/scroll by dragging the pen is crucial for me and it's broken by LinearMouse.

It would be nice if we could include/exclude just particular devices.

**Comment by lujjjh** [comment]
@Stooovie Thank you for your feedback.

LinearMouse supports per-device settings. Here's the device you are configuring:

<img width="400" alt="Screen Shot 2022-07-29 at 16 11 31" src="https://user-images.githubusercontent.com/3000535/181715040-9fbf221f-e452-4d64-8a04-1a534c191ac3.png">

By default, it automatically switches to the active device. You may also click it to choose a different device to configure.

I think you may have configured your Wacom tablet accidently or due to some bugs in device switching and detection.

If possible, please attach the configuration file and I'll check if there is something wrong in it.

**Comment by Stooovie** [comment]
You're right, I didn't notice the button - maybe it shows only when there's
multiple devices at the moment. It's now working as expected, fine.

Thanks!
Jiri

pá 29. 7. 2022 v 10:23 odesílatel Jiahao Lu ***@***.***>
napsal:
