### ISSUE TITLE
Preferences lag and frequently be stuck in macOS 10.15.7

### ISSUE THREAD

**Issue by Shiyang-Wang** [linearmouse/linearmouse#214]
10.15.7下界面卡顿，常假死

The user interface lags and is frequently stuck in macOS 10.15.7.

**Comment by lujjjh** [comment]
“界面卡顿”是指 LinearMouse 的偏好设置界面卡顿还是指启动 LinearMouse 后系统卡顿？

**Comment by Shiyang-Wang** [comment]
该软件偏好设置卡顿



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jiahao Lu ***@***.***&gt;
发送时间: 2022年7月23日 08:51
收件人: linearmouse/linearmouse ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [linearmouse/linearmouse] 10.15.7下界面卡顿 (Issue #214)





 
“界面卡顿”是指 LinearMouse 的偏好设置界面卡顿还是指启动 LinearMouse 后系统卡顿？

**Comment by lujjjh** [comment]
谢谢反馈。我没能复现这个问题。我会把这个 issue 翻译成英文来收集更多反馈。

Thank you for your feedback. I could not reproduce it. I'll translate this issue into English to collect more feedback.

https://user-images.githubusercontent.com/3000535/180594076-dd5d602f-dade-47d8-ad70-af6a2cfb1daf.mov

**Comment by BrushXue** [comment]
相同的问题，Pointer, Buttons和modifier keys都会让程序假死

**Comment by lujjjh** [comment]
> 相同的问题，Pointer, Buttons和modifier keys都会让程序假死

你好 @BrushXue，你也是用的 macOS 10.15.7 吗？

能否提供录屏和日志 (#117)，谢谢！

**Comment by BrushXue** [comment]
> > 相同的问题，Pointer, Buttons和modifier keys都会让程序假死
> 
> 你好 @BrushXue，你也是用的 macOS 10.15.7 吗？
> 
> 能否提供录屏和日志 (#117)，谢谢！

我也是10.15.7。程序我已经删了，找到了更好的替代品（https://github.com/noah-nuebling/mac-mouse-fix）

**Comment by lujjjh** [comment]
Hey, @howtheturntables!

Thank you for the screen recording! I think it really helps.

Does it only occur when navigate to another setting view (e.g.  from Scrolling to Pointer)?

I'm guessing it's due to some SwiftUI layout issue on Catalina. I'll see if I can workaround it. I still can't reproduce it on Catalina, so it would be helpful if you could verify it when the next beta version is published.

**Comment by domomg** [comment]
Hi, having the same issue on 10.15.7, going from a setting view to another gives me the beach ball for about 30 seconds.

Looking forward for the beta, will report as well if the issue is fixed.

**Comment by lujjjh** [comment]
I'm sorry for the wait.

I've published v0.7.4-beta.1 just now and hope it fixes this issue.
