### ISSUE TITLE
[Q] Is there a way to change pointer speed while having disabled pointer acceleration?

### ISSUE THREAD

**Issue by sambartik** [linearmouse/linearmouse#225]
Thank you for the beautiful app! So far I have experienced only one issue referenced in the title. I have tried changing pointer speed in system preferences and that seems to be unresponsive because of disabled pointer acceleration. Is there any other way to slow down the unaccelerated pointer speed? If it would possible, maybe having a nice slider underneath would be nice. :) Thanks!

**Comment by sambartik** [comment]
I am sorry, I somehow overlooked a big slider right underneath Acceleration slider, eh. However I have noticed that having checked the "Disable pointer acceleration" checkbox also disabled speed slider along with acceleration slider. I am a bit confused as though why is that? Is checking "Disable pointer acceleration" the same as setting acceleration to 0?

**Comment by lujjjh** [comment]
You are not the only one who has this question. Please refer to #201.

**Comment by sambartik** [comment]
> You are not the only one who has this question. Please refer to #201.

Thank you. That is what I was looking fot. Closing the issue.
