### ISSUE TITLE
Mousewheel Hotkey Bindings / Zoom

### ISSUE THREAD

**Issue by collinkreutzer** [linearmouse/linearmouse#227]
Thanks for linearmouse, i really enjoy using it. The only thing i really miss is the ability to map something like CMD + scroll to zooming (CMD & + and CMD & -) to allow zooming in PDF documents and the like. Some tools also allow mapping the scroll wheel to pinch to zoom but that does not alway work as well. Maybe this could be implemented and generalized by allowing key combinations as actions and the wheel up/down as buttons in button mappings?

**Comment by lujjjh** [comment]
Yes, I'm going to implement it :)

**Comment by lujjjh** [comment]
This feature is now supported in [v0.7.7-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.7-beta.2).
