### ISSUE TITLE
 Failed to save the configuration: You don't have permission to save the file "linearmouse" in the folder ".config"

### ISSUE THREAD

**Issue by dghayai** [linearmouse/linearmouse#230]
This error keeps popping up at start up and when attempting to make a change. I am the only user on this mac.
M1 Mac book pro.

Any fixes or solutions?

thanks

**Comment by lujjjh** [comment]
Duplicates of #197.

Could you please check the ownership and permission of your `~/.config` folder with Terminal.app:

```sh
ls -ld ~/.config
```

**Comment by lujjjh** [comment]
BTW, did you drag LinearMouse.app to Applications and ran it in Applications?

<img width="555" src="https://user-images.githubusercontent.com/3000535/183230758-2c57ff8e-dd33-4e44-99ae-5adba00666a5.png">

**Comment by dghayai** [comment]
i installed via brew and it says i own it but i dont see permissions

**Comment by lujjjh** [comment]
Thank you for your further information.

Permissions is shown like `drwxr-xr-x`.

Could you please check if LinearMouse is sandboxed?

1. Open Activity Monitor.app
2. Toggle View → Columns → Sandbox on
3. Search for LinearMouse and check if Sandbox column is Yes

<img width="468" alt="Screen Shot 2022-08-06 at 11 36 16" src="https://user-images.githubusercontent.com/3000535/183232187-1b13a22c-7500-4146-98e1-32cbe2246e0a.png">

<img width="1165" alt="Screen Shot 2022-08-06 at 11 36 50" src="https://user-images.githubusercontent.com/3000535/183232188-72a965e4-1ba5-4849-8a99-9323bb210829.png">

**Comment by dghayai** [comment]
the sandbox column displays "no"

**Comment by dghayai** [comment]
also
permissions display "drwx------"

**Comment by lujjjh** [comment]
> also permissions display "drwx------"

This means only the owner has permission to read / write / list the directory.

If its owner is correct, please check if the "User" column of LinearMouse in Activity Monitor is the same as the owner?

**Comment by dghayai** [comment]
The user "User" column of Linearmouse is the same as the owner.

**Comment by lujjjh** [comment]
That's weird...

Thank you very much and I'll try reproducing it on my Mac.

You may run the following command in Terminal.app and see if it can workaround this issue:

```sh
mkdir -p ~/.config/linearmouse
```

Though I'm guessing this is caused by incorrect configuration path calculated in the code. In that case, this workround might not work.

**Comment by dghayai** [comment]
The command had the output of "Permission denied".

**Comment by lujjjh** [comment]
It seems that this directory's permissions are still the problem.

You may run

```sh
sudo chown -R $(whoami) ~/.config
```

and see if it fixes the permission issue.

You will have to input your login password and hit enter.

**Comment by dghayai** [comment]
it worked i think ill reset to double check.

**Comment by lujjjh** [comment]
I'm not quite sure why this would happen.

A possible explanation is that the uid (id of the user) has changed. Maybe the `.config` directory was restored from a backup after a reinstallation of macOS.

Anyway, glad you've fixed it!

I will add a permission check in LinearMouse and do the fix for users.
