### ISSUE TITLE
最新版有bug

### ISSUE THREAD

**Issue by medmin** [linearmouse/linearmouse#239]
要求有accessbility permission，我反复试了多次，都不行，linearmouse总是觉得我没给权限

**Comment by medmin** [comment]
录像了，太大了，传不上来

**Comment by lujjjh** [comment]
你好！请问你是从 v0.6.1 之前升级的吗，有没有尝试过[将 LinearMouse 从权限中移除并重新添加](https://github.com/linearmouse/linearmouse/blob/main/ACCESSIBILITY.md#upgrade-from-v061-or-earlier-versions)？

如果还是有问题，方便的话麻烦将录像上传到任意网盘。谢谢！

**Comment by medmin** [comment]
> 你好！请问你是从 v0.6.1 之前升级的吗，有没有尝试过[将 LinearMouse 从权限中移除并重新添加](https://github.com/linearmouse/linearmouse/blob/main/ACCESSIBILITY.md#upgrade-from-v061-or-earlier-versions)？
> 
> 如果还是有问题，方便的话麻烦将录像上传到任意网盘。谢谢！

我install之后，去查看Accessbility权限，发现linearmouse已经打钩了，取消再加上，也无济于事

**Comment by medmin** [comment]
搞定了，原来是先remove，用那个减号去掉，再添加。。。。
