### ISSUE TITLE
Per app does not seem to work

### ISSUE THREAD

**Issue by ViRb3** [linearmouse/linearmouse#253]
This may be a configuration mistake on my side, so I apologize in advance. I am trying to get the "per-app" config to work, but it seems to have no effect.

My system:
- MacBook Pro M1 Max
- macOS 12.6
- LinearMouse 0.7.3
- Config: https://paste.gg/p/anonymous/5b82fc7f8d0d41fe812147b651dd8bcb

I tried adding the following to both the start and the end of the config file in:
```
~/.config/linearmouse/linearmouse.json
```

```json
    {
      "if" : {
        "app": "com.apple.Safari"
      },
      "pointer" : {
        "acceleration" : 0.01,
        "speed" : 0.01,
        "disableAcceleration" : true
      }
    },
```

I force quit LinearMouse between each attempt, but there is no change in the mouse behavior when using Safari. Any ideas?

Thanks!

**Comment by ViRb3** [comment]
Indeed, my configuration was incorrect. It seems like `disableAcceleration` disables `acceleration` and `speed`, so they had no effect. I kept `disableAcceleration` to `false` and then they worked!

**Comment by lujjjh** [comment]
> It seems like disableAcceleration disables not just acceleration but also speed

You are correct! You would see the comment if you were using editors like VS Code.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/3000535/191152892-a784f6f7-87ab-41f8-9dcc-4e17cba6451f.png">

You may also want to add a [device matching](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#device-matching) constraint, avoiding trackpads being affected:

```json
{
  "$schema": "https://app.linearmouse.org/schema/0.7.3",
  "schemes": [
    <other schemes...>,

    {
      "if": {
        "app": "com.apple.Safari",
        "device": {
          "category": "mouse"
        }
      },
      "pointer": {
        "acceleration": 0.01,
        "speed": 0.01
      }
    }
  ]
}
```

**Comment by ViRb3** [comment]
Yup, that's what I did now, I was just using that simple example for testing. Thanks for the awesome app!
