### ISSUE TITLE
This app broke the way my trackpad behaves

### ISSUE THREAD

**Issue by azkalex** [linearmouse/linearmouse#258]
I uninstalled it, restarted my laptop, and it's like even after all this, it's still keeping the settings added with LinearMouse. This is annoying. I expected to be back to macOS default settings for the trackpad after uninstalling it, but I'm not. I also used AppCleaner to remove it, and it removed all the configs, but it seems that this app overrides values in the original files since I have the same behavior I had with the app installed, even after I uninstalled it. Now I have to work with a buggy scroll because I don't know how to fully revert to the original macOS settings. Thank you.

M1 Pro, Monterey 12.6.

**Comment by lujjjh** [comment]
Hey, @azkalex!

What kinda buggy scroll? Could you attach a screen recording?

Technically, LinearMouse cannot modify the scrolling behavior if it is not running. You may check if there are still LinearMouse processes running in the Activity Monitor.

**Comment by lujjjh** [comment]
Thank you for your information.

According to your description, it seems that the scrolling inertia was disabled. You can find those settings in the System Preferences -> Accessibility -> Pointer Control -> Trackpad Options.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/3000535/192144233-516ff686-0c3e-4a09-8600-b19d45233b1e.png">

AFAIK, LinearMouse does not touch those settings. So, I'm guessing this might be set via other apps, or the System Preferences. If someone find it relavant to LinearMouse, please let me know.
