### ISSUE TITLE
Open in startup

### ISSUE THREAD

**Issue by Marcello1099** [linearmouse/linearmouse#260]
Even when adding the app to login items it is removed on its own

**Comment by lujjjh** [comment]
In the current version, LinearMouse will start at login unless you quit it in the menu.

If you are using 0.7.4-beta or later, there is a "Start at login" toggle in the menu.

---

> Even when adding the app to login items it is removed on its own

This is an expected behavior: https://github.com/linearmouse/linearmouse/issues/135#issuecomment-1161335796
