### ISSUE TITLE
Add support for profiles (configuration switcher)

### ISSUE THREAD

**Issue by tabrs** [linearmouse/linearmouse#264]
Hello,
this software is a must when you're about to play something. Main usage for me is to disable point acceleration before the gameplay, but there's no quick way to get it back when I'm done. I have to enter LinearMouse Preferences and hit the "Set default" button.

What about adding profiles? If I understood it correctly you should be having most necessary algorithms already implemented (like configuration reload).

If I can propose an MVP for this scenario, I'm totally okay to work with JSON configuration files, so it's okay for me to let an app behave following way

- In case there's only one configuration file in linearmouse directory, app works exactly the same way as it is now
- There's a new menu item "Profiles" with a single subitem named "Add new profile.." – the dialog asking for a name pops up when the menu has been activated by the user
- When user selects the name of the profile, configuration file is copied to a new file name which corresponds to a profile name entered by the user and configuration has been reloaded. Subitems in "Profile" menu now displays
   - Default profile
   - User named profile (checked – marked as selected)
   - --- (separator)
   - Add new profile
   - Delete current profile
- User can use LinearMouse application as usual, but all changes are written to a file that corresponds to selected profile
- Default profile can't be deleted
- When profile is tapped/clicked by the user then the corresponding configuration from a file is loaded. Configuration is reloaded when already selected profile is tapped/clicked.
- In case any configuration key-value is missing or invalid, it will fallback to a default configuration file. It it's missing there also, it will fallback to hardcoded app default.
- List of profiles is populated by the existence of all available and valid configuration files in linearmouse directory – for performance and anti-mess purposes it is okay to limit number of profiles to 5 (any number larger or equal to 3 will work :-))
- Nice to have: It would be nice to see all profiles (or at least those, marked as favorites) directly under the Linear Mouse icon, so I would not need to make another click when I would like to switch between two profiles (Gaming and Work)

Thank you for such a great tool! 👍

**Comment by lujjjh** [comment]
Thank you for your suggestion! (And translation!)

It seems that [app matching](https://github.com/linearmouse/linearmouse/blob/88df574122c4e9e8b9b1e09d737a1b4d8d8f18d6/Documentation/Configuration.md#app-matching) can cover your scenario. You can define multiple [schemes](https://github.com/linearmouse/linearmouse/blob/88df574122c4e9e8b9b1e09d737a1b4d8d8f18d6/Documentation/Configuration.md#schemes) in the configuration with conditions that activate them. For example, you can define a scheme that disables the pointer acceleration only when the games are activated. LinearMouse will turn on and off the pointer acceleration for you automatically.

However, in some cases, manually switching the profiles may be preferable. We can talk about whether such cases exist.

**Comment by tabrs** [comment]
Hello @lujjjh, sorry I just forgot to answer :-) yes, App Matching covers the scenario when I'm about to have specific settings for specific apps, anyway I would rather like to see an option where I can manually select profile from menu bar icon that covers my requirements at that moment.

Anyway this is something I can live without very perfectly, so it's up to you if it is something you are about to put into a roadmap or not. Feel free to close this enhancement request anytime – I promise I wont be offended :-)

Have a great day.
