### ISSUE TITLE
Horizontal scroll with modifier key?

### ISSUE THREAD

**Issue by dapicester** [linearmouse/linearmouse#267]
Hi, I am trying to migrate from [Mos](https://mos.caldis.me/). A part from the smooth scrolling, the only missing feature is to use a modifier key to trigger horizontal scroll.

If it may help, this is how Mos allow to configure it:
![Screen Shot 2022-10-21 at 14 52 56](https://user-images.githubusercontent.com/3007132/197131794-530bd82d-39e8-48c2-a9be-94e302104891.png)
Currently I have set it up so that when I scroll holding the shift key then it scrolls horizontally.

Would it be possible to add such a feature?

**Comment by lujjjh** [comment]
Hey, @dapicester!

If I am correct, you may configure it in Modifier Keys:

<img width="962" alt="Modifier Keys" src="https://user-images.githubusercontent.com/3000535/197146012-90126d8d-e4d7-47af-9f97-f0d9d9b665ca.png">

It is worth noting that holding shift to scroll horizontally is a default behavior when you are using a mouse wheel. Therefore, it might not always be needed to configure it if Mos is not running.
