### ISSUE TITLE
Strange Menu Bar Icon Behavior: Can't Disable/Enable

### ISSUE THREAD

**Issue by braddurbin** [linearmouse/linearmouse#271]
Since upgrading to v0.7.4, I could not get the menu bar icon to disappear by disabling it. I thought it was because I had also recently upgraded to macOS 13.0, but then I downgraded LinearMouse back to v0.7.3, and I can now disable the icon. I then tested this on another Mac running macOS 12.6, but it was doing the opposite with v0.7.4: not showing the icon even if I enabled it. I downgraded that one to v0.7.3, and that also fixed it there.

**Comment by lujjjh** [comment]
Thank you for your feedback!

I'm able to reproduce this bug. I'll fix it in the next release.

**Comment by realies** [comment]
@lujjjh, just installed linearmouse 0.7.4 on Ventura 13.0 and toggling the 'Show in menu bar' setting does not appear to do anything.

**Comment by lujjjh** [comment]
Hey, @realies!

I've just published [v0.7.5-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.5-beta.1) which includes this fix.

**Comment by realies** [comment]
@lujjjh, the new release works, thank you!
