### ISSUE TITLE
Rename `Preferences` to `Settings`

### ISSUE THREAD

**Issue by rakleed** [linearmouse/linearmouse#275]
`Preferences` became `Settings` in macOS Ventura: https://9to5mac.com/2022/11/01/mac-system-settings-macos-ventura/. Probably worth updating in LinearMouse as well.

**Comment by rakleed** [comment]
@lujjjh could you please also rename Preferences to Settings in all localization files?

**Comment by lujjjh** [comment]
> @lujjjh could you please also rename Preferences to Settings in all localization files?

Yes. Crowdin will do this in one hour.
