### ISSUE TITLE
Scroll Speed For Per App

### ISSUE THREAD

**Issue by mreser99** [linearmouse/linearmouse#278]
I'm wondering that can be happen? For example, when i'm using with 2 lines with google chrome, that's perfect. But same settings are slow on firefox. I should make it "3" for firefox but i don't wanna change each time.  

Long story short, is that possible to make?

**Comment by lujjjh** [comment]
Yes, you can define [app-specific schemes](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#app-matching).

**Comment by mreser99** [comment]
Thank you but it's complicated. I've tried but no success.

**Comment by hoefiger** [comment]
You can also change the value for `mousewheel.min_line_scroll_amount` in Firefox via [about:config](about:config]) (as stated here: https://www.maketecheasier.com/change-the-scrolling-speed-in-firefox/).

**Comment by mreser99** [comment]
> You can also change the value for `mousewheel.min_line_scroll_amount` in Firefox via about:config (as stated here: https://www.maketecheasier.com/change-the-scrolling-speed-in-firefox/).

Thank you mate. I did it same way.
