### ISSUE TITLE
macos Ventura: doesn't take effect until I switch to the settings window

### ISSUE THREAD

**Issue by benedictSchurwanz** [linearmouse/linearmouse#280]
When I turn on the computer, or turn on a mouse, for example a Magic Mouse 2, the pointer moves extremely slowly, until I open the LinearMouse settings, then the LM settings take effect.

**Comment by DrinkingJuice** [comment]
Yes,I have same question ,also on my magic mouse2 and magic trackpd

**Comment by lambegraham** [comment]
Also have this issue as posted

**Comment by lujjjh** [comment]
Fixed in [v0.7.6-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.6-beta.1).
