### ISSUE TITLE
Global settings for all mouse?

### ISSUE THREAD

**Issue by MariuzM** [linearmouse/linearmouse#281]
Could we have a global setting for all mouse? But exclude trackpads

**Comment by lujjjh** [comment]
Yes. You may edit the configuration file and prepend a scheme specific to mice. Please refer to [schemes](https://github.com/linearmouse/linearmouse/blob/5d2aa7bc2808f9420144a18950ef7797a9ea4680/Documentation/Configuration.md#schemes).
