### ISSUE TITLE
Small font in General settings for Update section

### ISSUE THREAD

**Issue by rakleed** [linearmouse/linearmouse#283]
Could you please make the font size in the General settings in the Update section the same as in the other sections? Since now it is smaller, and on a large screen, small text is inconvenient to read. And also the headings of the sections themselves would also be nice to increase.

<details><summary>Screenshot</summary>

![Screenshot 2022-12-05 at 18 03 46](https://user-images.githubusercontent.com/19418601/205671260-3ae51524-afbc-4930-9fa1-2c98ddd555ce.png)

</details>

LinearMouse 0.7.5, macOS 13.0.1.

**Comment by lujjjh** [comment]
Thanks for your feedback!

I'll make the font in the update section larger.

For the headings, I currently use [`Font.headline`](https://developer.apple.com/documentation/swiftui/font/headline) which seems to be the recommended font size for headings.
