### ISSUE TITLE
Disable mouse acceleration feature question

### ISSUE THREAD

**Issue by sussyboiiii** [linearmouse/linearmouse#285]
Hello, I recently found this programm and was wondering how this specific feature to disable mouse acceleration works because it doesn't seem to use this command "defaults write -g com.apple.mouse.scaling -integer -1" because its value always stays the same. It would be nice if someone could tell me. Im new to programming and my knowledge about Swift is basically zero so excuse me. Thanks!
<img width="621" alt="Bildschirm_foto 2022-12-11 um 19 14 42" src="https://user-images.githubusercontent.com/90244617/206921525-6e7c13b2-ff2f-4a68-a04f-520e29bacb8e.png">

**Comment by lujjjh** [comment]
You can refer to the code below:

https://github.com/linearmouse/linearmouse/blob/e8bc2cc4a2904f8c709b85ff4ecd946bb5f7774c/Modules/PointerKit/Sources/PointerKit/PointerDevice.swift#L146-L158

When `pointerAcceleration` of a `PointerDevice` is set to -1, its pointer acceleration is disabled.

For more information about this feature, please visit https://go.linearmouse.org/disable-pointer-acceleration-and-speed.

**Comment by lujjjh** [comment]
I'm not aware of any command that can disable pointer acceleration for a specific pointer device. That's why I need to write an app to do so.

The command you've mentioned actually sets the tracking speed of mouse to -1 in System Settings. I'm not sure what do you mean by it "doesn't seem to do the job for me."

**Comment by sussyboiiii** [comment]
So, Im trying to disable mouse acceleration and people said the the command I mentionned does so but I doesn't really change anything in my case so I was wondering how LinearMouse does it. The code snippet you gave me doesn't really give me any idea. Thanks

**Comment by lujjjh** [comment]
In principle, they do similar things, they both set the pointer acceleration to -1. Except that LinearMouse sets the pointer acceleration for a particular device, while the command you mentioned sets the global mouse acceleration. Also, you need to log out for the command to take effect. Maybe you do not have logged out after executing the command?

**Comment by sussyboiiii** [comment]
So I logged out after and checked it it was set to -1 and it was but i could still feel mouse acceleration. Oh and how does LinarMouse achieve turning it off without the user needing to log out first. Thanks
<img width="617" alt="Bildschirm­foto 2022-12-12 um 12 29 01" src="https://user-images.githubusercontent.com/90244617/207034520-ee4745fb-174e-4695-8674-41404d6a01b2.png">

**Comment by lujjjh** [comment]
System [APIs](https://en.wikipedia.org/wiki/API) are more low-level than the provided command-line utilities, so you have more control and flexibility when using them. For example, LinearMouse uses system APIs to read and write to [the I/O registry](https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/IOKitFundamentals/TheRegistry/TheRegistry.html) directly.

Of course, you can write a third-party command-line program to read and update the pointer acceleration of pointing devices in the I/O Registry with system APIs, but there is no such built-in utility on macOS.

**Comment by sussyboiiii** [comment]
Thanks
