### ISSUE TITLE
垂直线性滚动不如Scroll Reverser流畅，似乎有速度上限

### ISSUE THREAD

**Issue by woshiniming007** [linearmouse/linearmouse#288]
我是罗技Anywhere3鼠标，无极滚轮可以快速滚动，使用linearmouse和scrollreverser分别测试了反向线性滚动（速度调整成差不多），发现在多数程序中表现一样，但是某些程序里不如scrollreverser流畅，似乎有速度上限。例如在苹果的照片app中，还有PictureView中，下面是我录制的PictureView的两个软件的表现（照片app中表现类似）。

https://easyupload.io/o0sq2l

无极滚轮可以很快速地滚动，但linearmouse好像是反应有固定间隔一样，我无论再怎么加快滚动速度，都只能达到视频里那种上限，而且看起来还不流畅。linearmouse和scrollreverser在这部分的实现有什么不同吗？

**Comment by lujjjh** [comment]
你好！Scroll Reverser 并非线性滚动，滚动时存在加速度，因此你滚动得越快，滚动速度就会增加得越快。如果你更习惯有滚动加速度的情况，可以关闭 LinearMouse 中的线性滚动功能。

**Comment by woshiniming007** [comment]
> 

感谢回复，原来是这样。scrollreverser相对原版加速曲线的改动感觉还是挺好的。

另外请问LinearMouse我只用来改指针加速度，滚动相关选项不打勾时，同时使用scrollreverser会冲突吗？

**Comment by lujjjh** [comment]
> 我还是觉得linearmouse的滚动速度有上限 [...] 明显感到线性滚动到了一定速度后，再加快滚轮还是这个速度

这个现象是合理的。

你可以认为滚动这个动作的频率是有上限的。当加速到一定速度时，你的鼠标可能就以固定的频率发送滚动事件了，只是事件中附带的滚动距离数据会越来越大。开启线性滚动后，会忽略事件中的距离数据，每次都会滚动固定的距离。这也是速度有上限的原因。所以对于触控板、Magic Mouse 或者无极滚轮我不会推荐开启线性滚动，否则体验会很奇怪，会感觉实际滚动的距离与物理上不匹配；相反地，对于传统的滚轮我会推荐开启线性滚动，否则滚动加速度也会让人有同样的感觉。

Scroll Reverser 没有改变系统原有的加速度曲线，它是根据你设置的速度，在原有的滚动距离的基础上乘上了一个系数，从而使滚动距离整体变快或者变慢。

> 另外请问LinearMouse我只用来改指针加速度，滚动相关选项不打勾时，同时使用scrollreverser会冲突吗？

完全没有问题。

**Comment by woshiniming007** [comment]
明白了，多谢大佬。我理解是滚轮和移动一样，系统设置里那个是调的“加速度”，scrollreverser调的是“速度”，而LinearMouse目前是提供了完全关闭加速度的选项。若是以后有空，或许能搞得和移动一样，也能调加速度、速度数值？

**Comment by lujjjh** [comment]
感谢你的建议，我觉得可以有这个功能。

**Comment by woshiniming007** [comment]
谢谢，期待能够实现，这样scrollreverser的功能就是子集了，不用开两个软件了

**Comment by lujjjh** [comment]
合并至 #301

**Comment by lujjjh** [comment]
[v0.7.6-beta.4](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.6-beta.4) 中已支持调整滚动速度。
