### ISSUE TITLE
Apple Magic Mouse Unexpected behaviour

### ISSUE THREAD

**Issue by lambegraham** [linearmouse/linearmouse#291]
With the latest version of Apple Magic Mouse and v0.7.5, when turning the mouse on or reconnecting the mouse to the Mac, the cursor speed is much much slower than expected. I would estimate Speed: 0 would be what it reverts to. It can be fixed by opening the LinearMouse application and will fix this instantly. This happens on login and every time the mouse is turned off and reconnected. It is quite annoying having to open the application every time to fix this.

Settings are "Acceleration": 0 and "Speed": 0.12, and "Disable pointer acceleration": Unchecked
MacBook M1 Air 2020 Edition Monterey 12.6

**Comment by lambegraham** [comment]
Can confirm I have auto switch to active device ticked and also have same issue as others, specific to Apple Magic Mouse 2 and not reproducible with any other wireless mice

**Comment by lujjjh** [comment]
Duplicates of #209, #280.

Looks like it's time for me to buy a Magic Mouse 2 :)

**Comment by lujjjh** [comment]
Fixed in [v0.7.6-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.6-beta.1).
