### ISSUE TITLE
Add option to disable horizontal scrolling

### ISSUE THREAD

**Issue by chrisequalsdev** [linearmouse/linearmouse#296]
I am using a Magic Mouse 2 and there is no way to disable horizontal scrolling outside of several paid apps such as [this](https://ryanhanson.dev/scroll) one. The linearmouse option to reverse horizontal scrolling works with this mouse (contrary to #91) so it would seem that implementing an option to disable it wouldn't be much more work.

**Comment by lujjjh** [comment]
Interesting. I've implemented this feature by allowing zero scrolling distances in linear scrolling settings.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3000535/211176202-c13c008b-9240-46c9-b84f-128c61fdcc36.png">
