### ISSUE TITLE
Increase scroll speed without enabling Linear scrolling option (for Magic Mouse 2)

### ISSUE THREAD

**Issue by chrisequalsdev** [linearmouse/linearmouse#301]
With the Magic Mouse 2, enabling linear scrolling doesn't seem to work like with other devices. It seems to still accelerate with small movements even with inertia scrolling disabled in Accessibility options. I actually find that I get ideal scrolling with this mouse using these settings:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/77943337/212440994-a637e256-71b0-466b-90d0-0999fd3a7313.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/77943337/212441020-d93c1547-1d31-4006-9ead-4ef1ea074381.png">

However - only when the control key is pressed. An option to permanently scale scroll speed (using the function the Modifier Keys are using) outside of enabling Linear scrolling would be great. I realize this is a bit outside of what you designed this app for so if it's not something you want to add, perhaps point out a way to modify the code and I will build it myself?

**Comment by lujjjh** [comment]
This feature has been implemented in [v0.7.6-beta.4](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.6-beta.4).
