### ISSUE TITLE
[Feature] Option to switch back and forward buttons

### ISSUE THREAD

**Issue by cupboardunderscore** [linearmouse/linearmouse#313]
### Describe the solution you'd like

Have an option to switch back and forward side buttons on a mouse

**Comment by lujjjh** [comment]
Thanks for the feedback.

Do you mean swapping the back and forward buttons?

**Comment by cupboardunderscore** [comment]
> Thanks for the feedback.
> 
> Do you mean swapping the back and forward buttons?

Yes, this is what I meant.

**Comment by cupboardunderscore** [comment]
thank you!
