### ISSUE TITLE
[BUG] Swiping with four fingers gets reversed

### ISSUE THREAD

**Issue by keyboord01** [linearmouse/linearmouse#323]
### OS

macOS 13.1 (Build 22C65)

### LinearMouse

v0.7.6

### Describe the bug

swiping with four fingers gets reversed after the app is launched

**Comment by lujjjh** [comment]
I cannot reproduce it. Could you attach the configuration file and a screen recording?

You could find the configuration file here:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/3000535/215073677-1efe4393-e3ed-4130-b6f0-50b87cfba40a.png">
