### ISSUE TITLE
[Feature] 新版对滚轮的调节依然与Scroll Reverser不同

### ISSUE THREAD

**Issue by woshiniming007** [linearmouse/linearmouse#331]
### OS

macos 12.6

### LinearMouse

0.7.6

### Describe the solution you'd like

您好！非常感谢能够实现对滚轮速度的调节。在#288 您分析了与Scroll Reverser的差异，但我通过试用0.7.6版本，发现依然无法实现Scroll Reverser的效果。具体来说，对于无极滚轮，目前虽然LinearMouse可以调速度系数了，但不管速度大小，滚轮缓慢滚动时页面移动距离都会非常小，而Scroll Reverser则是可以有单次滚动的下限，比如至少跳好几行，感觉这样更符合windows的习惯。看起来Scroll Reverser并不是直接调的速度系数啊？

**Comment by lujjjh** [comment]
我看了一下 Scroll Reverser 的实现，它对离散滚轮做了特殊处理，效果像以行为单位的加速。我考虑一下产品上怎么融入这种模式。

另外，可否看下 Scroll Reverser 的日志（按住 option 的同时点击状态栏图标），在普通滚动和无极滚动切换时，continuous 的值是否发生了变化？

**Comment by woshiniming007** [comment]
你好，我测试了罗技的G502和Anywhere3，这两个都是无极滚轮，似乎从debug信息看，无极和“普通”模式并没有什么不同，只是有没有阻尼而已，continuous都是no？

截图在这：https://easyupload.io/8llreu

**Comment by lujjjh** [comment]
请更新到 [v0.7.7-beta.3](https://github.com/linearmouse/linearmouse/releases/tag/v0.7.7-beta.3)。

**Comment by woshiniming007** [comment]
感谢！我试用了一下，发现现在功能上一样，只是在量上有点不同。例如当两个软件调成单次离散滚动距离一样时，linemouse加速度明显大于scrollreverser，感觉是太灵敏了一点。而当两者调成加速度一样时，又感觉linemouse单次离散滚动距离太小了。换句话说，在正常人使用的加速度系数范围内，启用离散选项带来的变化不是特别大，单次离散滚动距离稍有点小了，我是感觉这样。

**Comment by woshiniming007** [comment]
谢谢！

Windows我感觉对无极滚轮而言，大概是滚动多快移动就有多快（当然记忆可能有偏差）。而“按行”和“按像素”当物理滚动速度快到一定程度时感觉有上限，使用“按行”在chrome等应用下感觉还可以，但在某些app如照片、PictureView里感觉有问题，如我之前提的#288，使用“按像素”的话在这俩app没问题了，在VSCode里移动距离又过大。

我理解目前两个软件是这样，设d是鼠标滚轮单次物理移动距离，f(d,a)为mac的加速度函数：
```
ScrollReverser移动距离 = 如果d是1则为Cv，否则为[f(d,a)*v]
其中C是常数，速度系数v软件里可调，加速度a在系统设置里可调，软件里不可调

LineMouse移动距离 = f(d,a)*v
其中加速度a、速度系数v都在软件里可调
```

你看我理解的对吗？我感觉目前的版本可以调的比较顺手了。

**Comment by lujjjh** [comment]
你的理解大致是正确的。不过 LinearMouse 也不会修改 Mac 系统的加速度函数。

假设 $d$ 就是系统计算出的移动距离（带加速度），Scroll Reverser 和 LinearMouse 都是基于 $d$ 进行改写。

除此之外，能知道滚轮滚动的格数 $\text{steps}$。

Scroll Reverser 的策略是：

$$ d'=
\begin{cases}
C \cdot \text{step size} & \text{steps}=1 \\
d \cdot \text{step size} & \text{steps}\ge 2
\end{cases} $$

LinearMouse 的策略是：

$$ d' = \text{acceleration} \cdot d + \text{speed} $$

Scroll Reverser 的策略的缺点是这个函数大概率不是连续的， $\text{steps}=1$ 和 $\text{steps}\ge 2$ 过渡时可能会产生明显的跳变。

LinearMouse 假定系统的滚动加速度是恒定的（实际上可能是更复杂的模型），即 $d\propto a$，则变换后有

$$ a' = \text{acceleration} \cdot a $$

其中，当 $\text{acceleration}$ 取 $1$ 时， $a' = a$；当 $\text{acceleration}$ 取 $1$， $\text{speed}$ 取 $0$ 时， $d'=d$。

**Comment by woshiniming007** [comment]
谢谢！原来LinearMouse目前是加，怪不得我感觉不像是乘，但不敢假定。

另外目前指针部分的调节，会覆盖系统设置里的滑块。滚轮的速度还是会受设置里“滚动速度”的影响的，不知道是不是那个 $a$，如果 $d\propto a$，那不如像指针一样覆盖掉系统设置，只需软件内参数一样就能保持一致的效果。当然如果 $d\not\propto a$，软件里“加速度”改成调系统设置那个值，不知道是什么样，估计效果也差不多吧。

**Comment by lujjjh** [comment]
指针速度调节跟滚动速度调节不同，前者是修改鼠标设备的分辨率，后者是拦截滚动事件、修改滚动的距离，所以很难做成完全一致的逻辑。

> 滚轮的速度还是会受设置里“滚动速度”的影响的 [...] 只需软件内参数一样就能保持一致的效果

目前来看这似乎并不是大问题。

我先关闭这个 issue 了，如果有更多问题欢迎随时重新打开。
