### ISSUE TITLE
[Feature] You should code a feature that pats you on the back for a job well done!

### ISSUE THREAD

**Issue by jrmiller82** [linearmouse/linearmouse#332]
### Is your feature request related to a problem?

Thank you thank you thank you for writing this software. I was about to rip my hair out of my head dealing with not being able to turn off mouse acceleration. 

### Describe the solution you'd like

Thank you thank you thank you for writing this software. I was about to rip my hair out of my head dealing with not being able to turn off mouse acceleration. 

### Describe alternatives you've considered

Thank you thank you thank you for writing this software. I was about to rip my hair out of my head dealing with not being able to turn off mouse acceleration. 

### Additional context

Thank you thank you thank you for writing this software. I was about to rip my hair out of my head dealing with not being able to turn off mouse acceleration.

**Comment by lujjjh** [comment]
Glad it helps :)
