### ISSUE TITLE
[Enable Linear Mouse for Apps like VLC Player] 

### ISSUE THREAD

**Issue by divindivakar** [linearmouse/linearmouse#344]
### OS

macOS 13.2 (Build 22D49)

### LinearMouse

v0.7.6

### Is your feature request related to a problem?

Thank you for this wonderful app it helps a lot with my natural actions. However , it is still not working within apps like VLC player as the volume functionality increase or decrease through mouse is as per default mac settings.

### Describe the solution you'd like

Please provide the linear app functionality in VLC player

**Comment by lujjjh** [comment]
Hi, @divindivakar!

Thanks for your feedback.

Do you mean that LinearMouse's reverse scrolling unexpectedly reversed the volume increasing and decreasing in VLC?

**Comment by pavelzw** [comment]
In VLC, the volume scrolling gets broken when you activate linear scrolling, I had the same problem too.

You can fix this by adding a custom rule for VLC using [App Matching](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#app-matching) in the configuration file.

**Comment by lujjjh** [comment]
Per-app settings GUI has been implemented in [v0.8.0-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.8.0-beta.1).
