### ISSUE TITLE
Support JSON5

### ISSUE THREAD

**Issue by pavelzw** [linearmouse/linearmouse#345]
### OS

macOS Ventura

### LinearMouse

v0.7.6

### Describe the solution you'd like

It would be nice to have support for JSON5 for the configuration file to explain certain lines in it.

**Comment by lujjjh** [comment]
Thanks for the suggestion!

I'd also like to support JSON5. However, I've encountered several technical problems when trying to support it:

- [`KeyDecodingStrategy.allowsJSON5`](https://developer.apple.com/documentation/foundation/jsondecoder/3766916-allowsjson5) requires macOS 12.0+ while the minimum target of LinearMouse is macOS 10.15.
- How to preserve the JSON5-specific elements (like comments) when encoding / decoding the configuration? In particular, it's not expected that the comments will removed when touching the settings on the GUI.

To support JSON5, it seems that I need to implement a JSON5 parser and encoder, and change the structure of the unserialized configuration to store JSON5 metadata.

Any technical suggestions and Swift JSON5 library recommendations are welcome.

**Comment by pavelzw** [comment]
> How to preserve the JSON5-specific elements 

One option, admittedly not the best but probably one of the easier ones, would be to warn the user before overwriting the comments (only when comments detected) and let them choose not to apply the changes made in UI (maybe show a diff too?).

The ones that are more likely to use comments in their configuration file are probably also the ones that don't really use the UI for configuration...

**Comment by pavelzw** [comment]
Switching to YAML would also be an alternative...

**Comment by lujjjh** [comment]
> The ones that are more likely to use comments in their configuration file are probably also the ones that don't really use the UI for configuration...

Probably. Is it a good idea to enable JSON5 decoding only on macOS 12+?

> Switching to YAML would also be an alternative...

I think the problem still exists...libyaml does not support emitting comments either (yaml/libyaml#42). And the YAML specification is much more complicated than JSON(5), so if we switch to YAML, it's almost impossible to reimplement the YAML parser and serializer, although there are some nice features in YAML, like anchors.

**Comment by lujjjh** [comment]
To support comments in JSON, [JSONC](https://code.visualstudio.com/docs/languages/json#_json-with-comments) can be a good start and its parser does not seem difficult to implement.

**Comment by 0xdevalias** [comment]
I see that at least partial support for json with comments was added, does that make this issue done now?

- https://github.com/linearmouse/linearmouse/pull/372

**Comment by pavelzw** [comment]
Yeah, at least decoding would cover my use-cases :)
