### ISSUE TITLE
[Feature] Per-app settings

### ISSUE THREAD

**Issue by burning** [linearmouse/linearmouse#350]
### OS

macOS 版本13.2.1（版号22D68）

### LinearMouse

v0.7.7

### Is your feature request related to a problem?

In adobe's software, scrolling becomes very fast

### Describe the solution you'd like

hope to add the function of excluding software list.

**Comment by lujjjh** [comment]
Hey, @burning!

Thanks for the feedback.

Currently, you can manually edit the configuration to add an app-specific scheme using [app matching](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#app-matching).

**Comment by lujjjh** [comment]
Per-app settings GUI has been implemented in [v0.8.0-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.8.0-beta.1).
