### ISSUE TITLE
[Feature] Use control+MouseSideButtons to navigate Desktops

### ISSUE THREAD

**Issue by cyril-marketfeed** [linearmouse/linearmouse#351]
### OS

macOS 13.2 (Build 22D49)

### LinearMouse

v0.7.6

### Is your feature request related to a problem?

I am so frustrated that I have to take my hand off the mouse when I need to switch Mission Control desktops. 
Which is done with control+LeftArrow and control+RightArrow by default in MacOS.
We do this 100s-1000s of times a day.
So this small feature will positively impact humanity in a substantial way.

### Describe the solution you'd like

I want to use control+MouseForwardSideButton and control+MouseBackwardsSideButton to move between the virtual desktops of Mission Control.

### Describe alternatives you've considered

The built-in MacOS keyboard shortcuts do not let you use mouse mouse buttons for any keyboard shortcut.

### Additional context

<img width="714" alt="Screenshot 2023-02-16 at 5 13 04 PM" src="https://user-images.githubusercontent.com/115976437/219355996-b9b5594b-d32b-4e15-af88-ebea1d95a649.png">

<img width="714" alt="Screenshot 2023-02-16 at 5 07 34 PM" src="https://user-images.githubusercontent.com/115976437/219356174-6356cde0-0296-4ad3-89a0-b396197253a5.png">

**Comment by lujjjh** [comment]
Thanks for the feedback!

This can be done by manually editing the configuration for the moment. Please refer to [this example](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#switch-spaces-desktops-with-the-command--back-and-command--forward).

The GUI of button mappings is tracked in #320.

**Comment by cyril-marketfeed** [comment]
OK thanks for the info.

**Comment by lujjjh** [comment]
Closing via https://github.com/linearmouse/linearmouse/pull/386.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/3000535/229305910-38b2f629-cb10-4a25-8da2-a18850f5f82a.png">

**Comment by da-revo** [comment]
Woah thanks a lot for the hard work.
