### ISSUE TITLE
[Feature] Add numeric value input field in addition to the sliders in Accelerated scroll mode

### ISSUE THREAD

**Issue by eugenesvk** [linearmouse/linearmouse#353]
### OS

macOS 10.15.7

### LinearMouse

0.7.7

### Is your feature request related to a problem?

I'd like to have more precise control over the scrolling behavior
Unfortunately, sliders don't show the precise values and also don't allow you to tweak/revert your tweaks in a precise manner (without a numeric value it's hard to remember and set the exact settings)

### Describe the solution you'd like

In addition to the current sliders there should be an input field with numeric values that shows the current settings and also allows you to change them

Ideally it'd show history of your most frecent values

**Comment by lujjjh** [comment]
Implemented in [v0.8.0-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.8.0-beta.2).

**Comment by eugenesvk** [comment]
Thank you for a quick fix!
