### ISSUE TITLE
[BUG] Scrolling speed not working when acceleration is set to zero

### ISSUE THREAD

**Issue by lujjjh** [linearmouse/linearmouse#356]
### OS

macOS 13.1 (Build 22C65)

### LinearMouse

v0.8.0-beta.1

### Describe the bug

Introduced in #348.

**Comment by jfd02** [comment]
Facing the same issue as well, scrolling works on most applications however the VS Code editor doesn't allow me to scroll. Moving the acceleration slider a little bit allows scrolling again

**Comment by lujjjh** [comment]
Fixed in [v0.8.0-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.8.0-beta.2).
