### ISSUE TITLE
[BUG] Pointer settings not applied after mouse reconnects

### ISSUE THREAD

**Issue by Kyzerii** [linearmouse/linearmouse#357]
### OS

macOS 13.0.1 (Build 22A400)

### LinearMouse

v0.7.7

### Is your feature request related to a problem?

when my mouse (Magic Mouse 2) disconnects like when I charge it or I turn it off and on, the pointer speed gets reset to default even though linear mouse is open all the time and then I have to open linear mouse settings from the menu bar before the pointer settings get applied

### Describe the solution you'd like

is there a way to get it to continue using my pointer settings automatically after my mouse reconnects

### Describe alternatives you've considered

happens to my mx master 3 and 3s too. only work around is to open the settings page and then your settings get re applied

**Comment by lujjjh** [comment]
Thanks for your feedback!

From your description, it sounds like a bug because LinearMouse is designed to automatically apply the pointer settings after your mouse reconnects.

Similar reports on Magic Mouse 2 can be found in #209, #280. I bought a Magic Mouse 2, reproduced that issue, and (I thought I) fixed it in v0.7.6. It's weird that you can reproduce this issue with v0.7.7, and it's not even Magic Mouse specific.

Is this consistently reproducible with Magic Mouse 2 and your other mice each time they are reconnected, including when you restart your Mac?

What Mac device are you using? It would be helpful if you could attach the logs (#117) while your mouse is reconnected.

**Comment by Kyzerii** [comment]
I use a 2021 mbp 16" M1 Pro. it always happens when the mouse reconnects. after restarts too.
![Screenshot 2023-02-19 at 17 31 13](https://user-images.githubusercontent.com/125812613/219964944-8e8ec8e1-e87d-4756-b666-a96a8405a026.png)
 Magic Mouse or not. I opened the console app but when I click view there's no option to include debug messages. but I did it anyways and this is what came up.

default	17:35:52.744709+0000	LinearMouse	Released connection: D7560B78-8F1B-4F5D-988B-3F132570F2FD
{
    UUID = "D7560B78-8F1B-4F5D-988B-3F132570F2FD";
    caller = "IOKit: IOHIDCopyHIDParameterFromEventSystem + 64";
    dispatchQueue = 0;
    eventCount = 0;
    eventMask = 0;
    port = 51051;
    resetCount = 0;
    runloop = 0;
    services =     (
        4294968511,
        4294968367,
        4294968465,
        4294968419,
        4294968563,
        4294968756,
        4294968373,
        4300568121,
        4294968517,
        4294968471,
        4294968425,
        4294968569,
        4294968762,
        4294968379,
        4294968523,
        4294968667,
        4294969145,
        4294968716,
        4294968477,
        4294968621,
        4294968431,
        4294968575,
        4294968719,
        4294969629,
        4294968385,
        4294968529,
        4294968768,
        4294968722,
        4294968483,
        4294968627,
        4294968676,
        4294968437,
        4294968581,
        4294967959,
        4294968774,
        42949683
error	17:35:52.748400+0000	LinearMouse	Unable to serialize CFObject: Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')
default	17:36:00.049124+0000	LinearMouse	Released connection: A13799E4-BEC7-4A9A-9445-E2B661C4AC78
{
    UUID = "A13799E4-BEC7-4A9A-9445-E2B661C4AC78";
    caller = "IOKit: IOHIDCopyHIDParameterFromEventSystem + 64";
    dispatchQueue = 0;
    eventCount = 0;
    eventMask = 0;
    port = 20587;
    resetCount = 0;
    runloop = 0;
    services =     (
        4294968511,
        4294968367,
        4294968465,
        4294968419,
        4294968563,
        4294968756,
        4294968373,
        4300568121,
        4294968517,
        4294968471,
        4294968425,
        4294968569,
        4294968762,
        4294968379,
        4294968523,
        4294968667,
        4294969145,
        4294968716,
        4294968477,
        4294968621,
        4294968431,
        4294968575,
        4294968719,
        4294969629,
        4294968385,
        4294968529,
        4294968768,
        4294968722,
        4294968483,
        4294968627,
        4294968676,
        4294968437,
        4294968581,
        4294967959,
        4294968774,
        42949683
error	17:36:00.051044+0000	LinearMouse	Unable to serialize CFObject: Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')

**Comment by lujjjh** [comment]
Oops, the "Include Debug Messages" is under "Action", not under "View". I've fixed the typo. Could you please try it again?

Any feedback on this issue from other M1 users, whether positive or negative, is also welcome.

**Comment by Kyzerii** [comment]
when I run it, nothing comes up unless I start scrolling with the mouse, and then I just reports changes to position. but its weird because the bug has somehow fixed itself and now my setting settings apply when my mouse reconnects.

**Comment by lujjjh** [comment]
The following logs should appear when the mouse is reconnected:

```
debug	10:33:23.857368+0800	LinearMouse	Device added: USB Receiver (VID=0x046D, PID=0xC52B)
debug	10:33:23.858450+0800	LinearMouse	Update pointer speed for device: USB Receiver (VID=0x046D, PID=0xC52B): 0.378600
debug	10:33:23.869013+0800	LinearMouse	Update pointer acceleration for device: USB Receiver (VID=0x046D, PID=0xC52B): 0.100000
```

I'll leave this issue open. If it happens again, please check the log to see if the pointer speed and acceleration are set correctly.
