### ISSUE TITLE
debounce time

### ISSUE THREAD

**Issue by couldbcoral** [linearmouse/linearmouse#360]
### OS

macOS 13.0 (Build 22A380)

### LinearMouse

v0.7.7

### Describe the solution you'd like

I don't know wether it is possible to do this within this app but it would be amazing if you added the capability to edit the debounce time of the right/left click

**Comment by lujjjh** [comment]
Thanks for the feedback. I guess this feature is for those random double-clicking mice where the microswitches wear out?

**Comment by couldbcoral** [comment]
yes exactly

**Comment by lujjjh** [comment]
Could you try [this build](https://github.com/linearmouse/linearmouse/suites/11137656992/artifacts/568021708) (built from #362) and see if it works as you expected?

**Comment by couldbcoral** [comment]
this works great. thank you.
