### ISSUE TITLE
Add option to reverse "universal back-forward" button assignment

### ISSUE THREAD

**Issue by captain13chris** [linearmouse/linearmouse#364]
### OS

macOS 13.2.1 (Build 22D68)

### LinearMouse

v0.7.7

### Is your feature request related to a problem?

I'm always hitting the wrong button to go back on my mouse (Logitech G603). Currently, the "easier to reach" button is used to go forward while it is a little harder to reach the "back" button.

### Describe the solution you'd like

I'd like to have the option to reverse these two button assignments, meaning the "forward" and "back" buttons.

**Comment by captain13chris** [comment]
Okay, I just saw there already is an example on how this can be achieved within the config file. Sorry about that!

**Comment by captain13chris** [comment]
Okay, I just saw there already is an example on how this can be achieved within the config file. Sorry about that!

**Comment by lujjjh** [comment]
Currently it's only doable by editing the configuration file. Hopefully I can implement the GUI soon.
