### ISSUE TITLE
MAC Ventura 无法获得辅助功能授权

### ISSUE THREAD

**Issue by maotui** [linearmouse/linearmouse#366]
### OS

MAC Ventura 13.2.1

### LinearMouse

0.7.7

### Describe the bug

感谢大佬开发怎么好的软件，分享给大家使用。
汇报一个错误：之前一直使用macOS Monterey 12系统，本软件使用很方便，
最近更新到MAC Ventura 13.2.1，之前安装的版本失效，故升级到0.7.7版本。
安装后已成功授权了辅助功能，但界面一直滞留在“打开辅助功能页面”，无法开启软件。
具体见截图，感谢！
![iShot_2023-02-24_14 19 02](https://user-images.githubusercontent.com/126228901/221107514-b27206e4-6d28-46c6-bab0-ba1aaed7a79c.jpg)
![iShot_2023-02-24_14 18 11](https://user-images.githubusercontent.com/126228901/221107520-d3624f3b-fa2c-453b-ad97-3f0c51864334.jpg)

**Comment by lujjjh** [comment]
你好，感谢反馈。

如果是从 v0.6.1 或者之前的版本更新的，请参考[这个链接](https://go.linearmouse.app/accessibility-permission#upgrade-from-v061-or-earlier-versions)或者点击界面上的“获得更多帮助”，手动删除辅助功能权限中的 LinearMouse 项后重新添加。

**Comment by maotui** [comment]
以解决，非常感谢。
