### ISSUE TITLE
与截图工具shottr冲突，致使滚动截图功能故障 | LinearMouse breaks scrolling snapshots in Shottr

### ISSUE THREAD

**Issue by huangwch** [linearmouse/linearmouse#367]
### OS

macOS 版本12.6（版号21G115）

### LinearMouse

v0.7.7

### Describe the bug

与截图工具shottr（https://shottr.cc/）冲突，致使滚动截图功能故障

**Comment by lujjjh** [comment]
你好，感谢反馈！

已忽略来自 Shottr 的事件，可以尝试[这个构建](https://github.com/linearmouse/linearmouse/suites/11178465481/artifacts/571096076)（构建于 #368），看有没有解决你的问题。

这个变更会合入下一个 beta 版本。

**Comment by huangwch** [comment]
> 你好，感谢反馈！
> 
> 已忽略来自 Shottr 的事件，可以尝试[这个构建](https://github.com/linearmouse/linearmouse/suites/11178465481/artifacts/571096076)（构建于 #368），看有没有解决你的问题。
> 
> 这个变更会合入下一个 beta 版本。

非常感谢 ， 新版本，已解决截长图问题！
