### ISSUE TITLE
click debouncing 测量两次点击间隔方法精度不够

### ISSUE THREAD

**Issue by Nicify** [linearmouse/linearmouse#369]
### OS

macOS 13.2

### LinearMouse

v0.8.0-beta.3

### Describe the bug

https://github.com/linearmouse/linearmouse/commit/abc07c8df75e16a20b12b359b51531cc5f4c9230 新加的 click debouncing 中使用的 `timeIntervalSinceNow` 精度与实时性不够

![telegram-cloud-photo-size-5-6321264757117662572-y](https://user-images.githubusercontent.com/24217275/221172621-b981e131-b670-43ca-8cf3-4537b7409d7f.jpg)
应该用分辨率更高的 API 来测量两次鼠标点击的时间间隔 https://forums.swift.org/t/recommended-way-to-measure-time-in-swift/33326/

**Comment by lujjjh** [comment]
Good catch!

**Comment by Nicify** [comment]
上面 swift forums 链接里最下面提到的 dispatchtime 应该是更合适的 API
<img width="952" alt="Screenshot 2023-02-24 at 20 13 02" src="https://user-images.githubusercontent.com/24217275/221176359-199e7708-bc4a-40b8-b432-3005baac8dd5.png">
https://developer.apple.com/documentation/dispatch/dispatchtime

**Comment by lujjjh** [comment]
你的主题提到的 50-100 ms 是 timer 的精度，而不是 `timeIntervalSinceNow` 的精度，代码中没有依赖 timer。

但是这里依赖系统时间确实不妥，因为系统时间可能产生变动（而且 Swift 中 `timeIntervalSinceNow` 似乎不是单调的），所以当系统时间回拨的时候会造成错误地触发 debouncing。
