### ISSUE TITLE
Disable acceleration and etc when mouse connected

### ISSUE THREAD

**Issue by nikorue** [linearmouse/linearmouse#37]
a toggle so that the option enables it when system detects a mouse or when an app is launched (eg a game)

**Comment by lujjjh** [comment]
Hi, nikorue!

All of LinearMouse's current features, including disabling acceleration, are mouse-specific and should only affect the mouse. So you can always keep "disable acceleration" turned on if you like.

Of course, if you have run into any specific problems, please let me know. :)

**Comment by rakleed** [comment]
.
