### ISSUE TITLE
The same mouse pointer experiences differently on different monitors

### ISSUE THREAD

**Issue by mcxinyu** [linearmouse/linearmouse#373]
### OS

macOS13.1

### LinearMouse

0.7.7

### Describe the bug

My macbook is connected to another screen, and its resolution (3840*2160) is different from macbook. Under the premise of the parameters I set, the mouse pointer performs well on the macbook, but when it comes to the external monitor, the movement of the mouse pointer seems to be slowed down.

I've tried several LinearMouse versions, but the problem doesn't seem to be fixed.

**Comment by lujjjh** [comment]
你好，感谢反馈！

能否进一步描述“移动慢”具体的体验？同样的鼠标、同样的指针配置，实际的 DPI 体验应该是一致的，也就是说物理移动同样的距离，应该对应屏幕上移动同样的逻辑像素。

当然，如果两块屏幕的 PPI 差异比较大，那么即便指针移动过的逻辑像素是一样的，可能也会在体感上带来速度差异。比如同一块屏幕，分别设置为“More Space”和“Larger Text”，光标在前者就会比在后者体感上移动速度更慢，不知道你说的“移动慢”是不是这种体验。

**Comment by mcxinyu** [comment]
你好，在外接显示器上感觉就是不跟手，反应有点滞后。但是用机器自带的触控板却没有这个差别。

**Comment by lujjjh** [comment]
外接显示器的刷新率是否与内建显示器一致？如果只是不跟手，可能显示器与刷新率低有关。

**Comment by mcxinyu** [comment]
> 外接显示器的刷新率是否与内建显示器一致？如果只是不跟手，可能显示器与刷新率低有关。

感谢你的提醒，mac 是120 外接显示器是 60，我找时间设置下相同的刷新率看看。
