### ISSUE TITLE
Horizontal scroll (MX master 3)

### ISSUE THREAD

**Issue by manueltedesco** [linearmouse/linearmouse#375]
### OS

macOS Versión 13.2.1 (Compilación 22D68)

### LinearMouse

v0.7.7

### Describe the bug

The horizontal scroll wheel in photoshop using the MX Master 3 (that acts a s a zoom in) when using llinear mouse gets recognized as vertical. So the changes you make to the vertical behaviour of the vertical mouse wheel get also applied to the horizontal one.

### To reproduce

1. You need an MX Master 3 mouse (at least that's the one that I'm using, not sure if it happens on all other MX devices as well)
2. Have the Photoshop customized buttons on photoshop enabled in the Logi options + app (or just select that the horizontal scroll wheel behaves as photoshop zoom in on the Logi options + app)
3. Make a new file in photoshop and use the wheel to zoom in/out.
4. Change the vertical scroll wheel behaviour on the linear mouse app options and see it affect the horizontal zoom in photoshop.

### Expected behavior

These changes to the horizontal wheel should only happen when, in Linear Mouse, you change the setting of the horizontal scroll behaviour, not the vertical.

**Comment by lujjjh** [comment]
Thanks for your feedback!

I don't have an MX Master 3, however, from your description I'm guessing that Logi Options+ converts horizontal scrolling to option+vertical scrolling, which is the gesture for zooming in/out in Photoshop.

One solution is not to modify the events sent by Options+, but this would also bypass the normal vertical scrolling events sent by Options+. LinearMouse cannot distinguish between them.

The other solution is to implement this feature in LinearMouse, but this takes time.

I think we can try the first approach for now, by adding a switch to stop modifying events sent by other processes, and see if it works properly.

**Comment by lujjjh** [comment]
Could you try [this build](https://github.com/linearmouse/linearmouse/suites/11231450317/artifacts/574931347) (built from #376)? Please make sure to check "Bypass events from other applications" in General settings.
