### ISSUE TITLE
LinearMouse using 50%+ CPU

### ISSUE THREAD

**Issue by jeremyjacob** [linearmouse/linearmouse#377]
### OS

macOS 13.2 (Build 22D49)

### LinearMouse

v0.7.7

### Describe the bug

LinearMouse uses more CPU than should be necessary, possibly an indication of unintentional loops or poorly optimized scroll-event-triggered code paths. This makes scrolling laggy, causing freezing every few seconds.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/44799944/221727613-716af857-8f7a-4c95-bfff-704be8c8e7ce.png">

### To reproduce

Unknown. CPU usage spikes when mouse is moving or scrolling only. Universal back/forward is not enabled. Scrolling and tracking are both accelerated with reasonable values. Issue occurs using built-in trackpad. I have not tried with other input devices.

### Anything else?

I am on a 2021 MBP with the M1 Pro.
[logs.txt](https://github.com/linearmouse/linearmouse/files/10845689/logs.txt)

**Comment by lujjjh** [comment]
Thank you for attaching the logs!

It seems that LinearMouse thought there were multiple internal trackpads toggling back and forth. Could you please open the device picker and check if there are multiple trackpads detected?

<img width="573" alt="Screenshot 2023-02-28 at 10 05 37" src="https://user-images.githubusercontent.com/3000535/221734575-8a045bd8-ffb5-449f-a12d-ec7bc6065639.png">

**Comment by jeremyjacob** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/44799944/221749872-75ac392d-8f10-4d85-b343-546e5881651d.png">
Looks like there's only one device. Also checked before restarting LinearMouse and IIRC it looked the same.

After restarting and using the machine for the past couple hours everything has been fine and CPU usage is below 5%.

Closing for now, thanks for your help. I'll re-open if this issue appears again.

**Comment by lujjjh** [comment]
I am not quite sure, but this may be related to "Auto switch to the active device". When you turned this off, the expensive code paths (recalculating the current scheme, which was removed in the latest beta) were bypassed, so CPU usage went back to normal.
