### ISSUE TITLE
Trackpad scrolling jumps-scrolls when shifting from mouse scrollwheel

### ISSUE THREAD

**Issue by Henzxon** [linearmouse/linearmouse#378]
### OS

macOS 13.2.1 (Build 22D68)

### LinearMouse

v0.8.0-beta.4

### Describe the bug

I'm using an MX Master 3 via USB Receiver.

When using scroll wheel on mouse the display scroll just fine but when I shiftback to trackpad scrolling, the screen jump-scrolls multiple lines maybe one view height of scroll.
https://www.loom.com/share/0cb574602baa4159bcfffbf1c941216f

### Anything else?

https://www.loom.com/share/4bcef8e565cf4b87902377111e3f3a06

**Comment by lujjjh** [comment]
Yeah, I noticed this issue earlier today. Will fix it soon.

Thanks for your report!

**Comment by lujjjh** [comment]
This issue should have been fixed in [v0.8.0-beta.5](https://github.com/linearmouse/linearmouse/releases/tag/v0.8.0-beta.5).
