### ISSUE TITLE
Vertical scroll jumps or is unresponsive

### ISSUE THREAD

**Issue by demiurge94** [linearmouse/linearmouse#381]
### OS

macOS 13.0 Ventura

### LinearMouse

v0.8.0

### Describe the bug

Installed the latest linearmouse on a brand new macbook air on Ventura and whenever linearmouse is running, scrolling on webpages seems to lag a bit before responding or responds in the opposite direction. I tried downgrading to 0.7.7 which I have on another mac where it runs just fine (except that one is still on Monterey), and I tried the latest beta release as well.

### To reproduce

In mac OS 13.0, just having linearmouse running breaks scrolling, using trackpad.

**Comment by lujjjh** [comment]
Thanks for your feedback!

Could you please attach the logs (#117) when reproducing this issue?
