### ISSUE TITLE
Mouse&Trackpad Option

### ISSUE THREAD

**Issue by xxS1xx** [linearmouse/linearmouse#382]
### OS

macOS 12.6.2 (Build 21G320)

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

My trackpad also losses pointer acceleration when I run this app.

### Describe the solution you'd like

Could you please provide an option to disable for trackpad and works only on external mouse

**Comment by lujjjh** [comment]
Hey @xxS1xx,

Please check the pointer settings for trackpad. If you've edit these settings, you can revert them to system defaults.

<img width="962" alt="Screenshot 2023-03-02 at 22 56 25" src="https://user-images.githubusercontent.com/3000535/222464650-184da0e0-e744-47e3-bbd6-4a932e50a851.png">
