### ISSUE TITLE
Disable Ctrl+LeftClick Shortcut

### ISSUE THREAD

**Issue by angaylo22** [linearmouse/linearmouse#384]
### OS

macOS 13.2.1 (Build 22D68)

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

This is not related to an issue that stops me from continuing to use linear mouse nor an urgent request but it is a suggestion to make the software better.

Usually when I'm playing games I get annoyed when I either have to rebind the crouch key/change its position on the keyboard. I have to rebind it because it forces me to right click instead of left. So far CS:GO is the only game that seems to have solved this issue. I'm not sure if this has been suggested yet or if there is are issues with implementing this iI really would like this feature added.

### Describe the solution you'd like

I'd like a setting to disable Control+Left Click. This could be similar to being able to disable Shift+Scroll(horizontal with Vertical Scrollwheel) by making the shift modifier key change scrolling speed and leaving it at the 1.00x option. I would just be an option in the dropdown menu instead of just being a workaround.

### Describe alternatives you've considered

Give us a way to remap the mouse buttons/remap modifier keys+mousebuttons. It would also be helpful If there are options to remap the backwards and forwards buttons to a different function besides backwards and forwards such as a different key or shortcut. While there are other programs that allow you to do stuff like this such as karabiner elements, I think implementing this feature will make linear mouse much better.

**Comment by lujjjh** [comment]
Closing via #386.
