### ISSUE TITLE
Dont have the ability to turn of my trackpad while mouse is plugged in (even when I set that up in the setting on my mac)

### ISSUE THREAD

**Issue by lovrobuday** [linearmouse/linearmouse#387]
### OS

macOS 13.2 (Build 22D49)

### LinearMouse

v0.8.0

### Describe the bug

Went to System setting -> Accesibility -> Turn off built in trackpad when mouse is detected. Doesnt happen, probably because all my mouse setting have been completely taken over by linear mouse. Even when I delete it it doesnt work HALLLLP

**Comment by lujjjh** [comment]
Hi @lovrobuday,

Thanks for your feedback. However, I can't reproduce this issue on my MacBook.

Could you provide more information?

* What model of MacBook are you using?
* Was this functionality being working *right before* LinearMouse was installed, with the same mouse connected? Is your mouse connected via dongle or Bluetooth?
* Have you installed Karabiner-Elements?
* Have you tried restarting your computer after uninstalling LinearMouse?
