### ISSUE TITLE
Add disable function to Lofree mouse

### ISSUE THREAD

**Issue by zyta2k** [linearmouse/linearmouse#391]
### OS

macOS 13.1 (Build 22C65)

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

I'm always frustrated with my Lofree mouse side buttons

### Describe the solution you'd like

I'd like to have a function that disable the zoom in zoom out event of my Lofree mouse

**Comment by lujjjh** [comment]
Closing via #386.

Now you can easily map the side buttons to "no actions" in v0.9.0-beta.1.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3000535/229333575-44adb6c3-13e1-4e68-9ea1-af1ce8b7a412.png">
