### ISSUE TITLE
AutoCAD 2023 不显示在应用列表中

### ISSUE THREAD

**Issue by KingfuChan** [linearmouse/linearmouse#392]
### OS

macOS 版本13.2.1（版号22D68）

### LinearMouse

v0.8.0

### Describe the bug

AutoCAD 2023 不显示在应用列表中，即使是开启app后也不显示。

### Anything else?

如果可以的话，希望增加手动选取软件的功能。

**Comment by lujjjh** [comment]
我尝试安装了 AutoCAD 2023，似乎在没有 license 的情况下没法打开主界面。

请切换到 AutoCAD 2023，然后点开 LinearMouse 状态栏菜单，查看是否有“为 AutoCAD 2023 配置...”的选项，点开应该就可以为 AutoCAD 2023 配置了。

**Comment by KingfuChan** [comment]
尝试了一下，明白了其中的情况，之前由于菜单栏一直隐藏图标，没留意到可以通过菜单栏选项进行设置。
