### ISSUE TITLE
Logitech g305 scroll not working

### ISSUE THREAD

**Issue by Nivekss** [linearmouse/linearmouse#394]
### OS

macOS 13.0 (Build 22A380)

### LinearMouse

v0.8.0

### Describe the bug

Scrolling doesnt work for g305 while the app is running

**Comment by lujjjh** [comment]
Hi @Nivekss,

Have you modified the scroll settings?

Please attach your configuration file:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/3000535/227156447-4dd500c9-bea5-4981-8c07-2713aa4381f4.png">

**Comment by plunderphonics** [comment]
Same issue, but it's only on some of my mice.

G305 Lightspeed: No scrolling works 
G502 Wired: Works as intended
G502 Lightspeed: Works as intended
Orochi V2 via Bluetooth: No scrolling works
Orochi V2 via USB dongle: No scrolling works

For the mice with issues, scrolling does not work period while LinearMouse is running, regardless if "Reverse scrolling" is on or not.

[linearmouse.json.zip](https://github.com/linearmouse/linearmouse/files/11074520/linearmouse.json.zip)

**Comment by lujjjh** [comment]
Hey @plunderphonics,

Have you tried reverting the scrolling acceleration and speed to the system defaults? When both acceleration and speed are set to zero, scrolling is disabled.

That's a feature you can use, for example, to disable horizontal wheel scrolling.

**Comment by plunderphonics** [comment]
I see, that is indeed the case! Very embarrassing for me to fail to realize that I was changing the scrolling acceleration and not the pointer. Thank you for the quick response.

**Comment by lujjjh** [comment]
Understood. In the next version I will add a warning message in the UI for this specific case.
