### ISSUE TITLE
When i click to many times my mouse start to slow down and cant keep up making me lose many games

### ISSUE THREAD

**Issue by skiesfr** [linearmouse/linearmouse#401]
### OS

MacOs ventura 13.2

### LinearMouse

v0.8.0

### Describe the bug

when i start clicking fast its start to go slow and cant keep up lagging and make me missing me all my shoots/swords

### Expected behavior

the next version this to be fixed

**Comment by lujjjh** [comment]
Is it possible that you accidentally enabled click debouncing?

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3000535/228563641-819597c7-caf5-4631-888b-eb83ab880e9e.png">

**Comment by skiesfr** [comment]
> 

where is that?

**Comment by lujjjh** [comment]
Is this still reproducible?
