### ISSUE TITLE
select Terminal.app and Finder.app

### ISSUE THREAD

**Issue by ysBach** [linearmouse/linearmouse#410]
### OS

macOS 13.1 (Build 22C65)

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

Cannot tune for Terminal and Finder

### Describe the solution you'd like

I wish I can tune the scroll for Finder & Terminal apps separately.

**Comment by lujjjh** [comment]
Duplicates of #392.

You can switch to Terminal or Finder, and configure them individually from the menu.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/3000535/229333148-54d3481b-b312-4306-b017-2cda06b0fcae.png">


But it makes sense to allow manual selection of applications. I'll work on adding that functionality.
