### ISSUE TITLE
Save the current configurations

### ISSUE THREAD

**Issue by ysBach** [linearmouse/linearmouse#411]
### OS

macOS 13.1 (Build 22C65)

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

I cannot export the settings as a file

### Describe the solution you'd like

I wish I can export/import settings file

### Describe alternatives you've considered

I

**Comment by lujjjh** [comment]
I think you might have hidden the menu bar icon. The configuration file can be found via Config → Reveal in Finder.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3000535/229332866-0907e767-7003-4d72-b258-d8cdeb1735a8.png">
