### ISSUE TITLE
Horizontal scroll settings not working (Logi G604)

### ISSUE THREAD

**Issue by lucascacho** [linearmouse/linearmouse#431]
### OS

macOS 13.3 (Build 22E252)

### LinearMouse

v0.8.0

### Describe the bug

Horizontal scrolling settings do not impact actual behaviour. I have tried all available settings but no changes are seen. Scrolling horizontally works very slowly. Vertical scrolling settings work fine.

Attaching settings file.
[linearmouse.txt](https://github.com/linearmouse/linearmouse/files/11191000/linearmouse.txt)

Btw, I am using Logitech G HUB, however scroll buttons are mapped to default settings (i.e: unchanged).

Appreciate your help!

### To reproduce

No particular steps. Just changing horizontal scroll settings and having my mouse I would guess.

### Expected behavior

Horizontal scrolling would behave according to the specified settings.

**Comment by lucascacho** [comment]
Yes! Apologies, that was a typo. i meant G604.

It does not have horizontal "wheels" per se, but it allows for tilting of the scroll wheel to scroll to either side. 

I now realise that this could just mean that this is an unsupported feature.

**Comment by lujjjh** [comment]
That sounds cool. So this is implemented in G HUB, right? That is, G HUB maps left tilting of the scroll wheel to left scrolling, and right tilting of the scroll wheel to right scrolling.

I'm guessing that left/right tilting of the scroll wheel actually triggers a button click. If so, you could try unassigning the left / right scroll tilting actions in G HUB and try assigning actions in the latest beta version of LinearMouse:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3000535/230933842-060ad439-81c3-48dc-9da4-d4e331e55383.png">

After unassigned actions in G HUB, press the Add button. If left / right tiltings can be recorded, you can assign Scroll Left / Right to them.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3000535/230935055-d846ed6f-147c-4074-9ece-fd83a67d0d2e.png">

**Comment by lucascacho** [comment]
When I unmap the "Scroll left" and "Scroll Right" buttons via G HUB, the application basically disables those buttons.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/29047781/230947906-3999b2b4-97d4-482a-bd2b-9d9639ad8942.png">

Just to validate this, I attempted to add a button via LinearMouse, but the buttons were not registered.


I re-enabled both buttons on G HUB and attempted to register the side buttons on LinearMouse and it is interpreting them as follows:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/29047781/230948385-477c7807-70d6-4ef9-9525-7772ec9d6a67.png">

![image](https://user-images.githubusercontent.com/29047781/230948425-1ea1ea00-a853-43fb-9f07-f9b11faea39c.png)

Perhaps this helps in providing some insight as to how this mouse works.

Thanks again for your help :)

**Comment by lujjjh** [comment]
Thanks for the information!

I'm curious what will happen to scroll wheel tilts after G HUB is quit. Will horizontal scrolling still be triggered or not? In this case, can the wheel tilts be registered in LinearMouse?

**Comment by lujjjh** [comment]
It doesn't seem to work quite the way I thought it would.

The next beta will make it easy to export detailed logs, and I'll ping you again and hope we can figure out why the horizontal scroll distance setting doesn't work.

Thanks again for reporting this. :)

**Comment by lucascacho** [comment]
I noticed it is working as expected now!

Was the app updated? currently on 0.9.0-beta.3

**Comment by lujjjh** [comment]
> I noticed it is working as expected now!
>
> Was the app updated? currently on 0.9.0-beta.3

🤣 That's weird, I haven't done anything yet.

**Comment by lujjjh** [comment]
Logs can now be exported in v0.9.0-beta.4.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3000535/233276532-be7e33db-e9f4-4d94-94eb-f2b2467bae77.png">

If you reproduce this problem again, please attach the logs. Thanks very much!
