### ISSUE TITLE
建议在按钮选项卡中增加全屏app切换功能

### ISSUE THREAD

**Issue by NoobMaster233** [linearmouse/linearmouse#444]
### OS

macOS 版本11.5.2（版号20G95）

### LinearMouse

v0.8.0

### Describe the solution you'd like

现在按钮选项卡下，有一个全局前进后退功能，实现的是app内的前进后退。可以增加一个全屏app切换的功能吗？谢谢

**Comment by lujjjh** [comment]
你好！请升级到最新的 beta 版本，然后为鼠标按键分配相应的动作：

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3000535/233263613-b6f05b36-6908-4938-a892-04446131b985.png">

**Comment by lujjjh** [comment]
正式版已包含该功能。

**Comment by NoobMaster233** [comment]
确实有了，确实很好用，吹爆这个软件！
