### ISSUE TITLE
missing privacy policy

### ISSUE THREAD

**Issue by CptTim** [linearmouse/linearmouse#454]
### OS

macOS 13.3.1 (Build 22E261)

### LinearMouse

v0.8.0

### Describe the solution you'd like

It would be nice if LinearMouse would have a privacy policy added, that states what, if any information from the user or device is collected (diagnostics, etc...).

### Additional context

should also be added to the website

**Comment by lujjjh** [comment]
The privacy policy is now available on the website: https://linearmouse.app/privacy.html
