### ISSUE TITLE
Display-dependent settings

### ISSUE THREAD

**Issue by gyro-labs** [linearmouse/linearmouse#460]
### Describe the solution you'd like

I would very much like the possibility to have different settings for different monitors. On my macbook screen, I want vastly different settings than on my ultrawide monitor. 

Is that technically possible?

**Comment by lujjjh** [comment]
This is doable, although the potential impact on performance needs to be further investigated.

**Comment by gyro-labs** [comment]
Alternatively, the ability to save presets would already be very useful. This would allow users to enable the "home desktop" preset when they're at home, and the "mac display" setup when they're on the move.
