### ISSUE TITLE
Moving mouse while scrolling on trackpad broke with 0.9.0

### ISSUE THREAD

**Issue by RyanHurst** [linearmouse/linearmouse#463]
### OS

macOS 13.3.1 (a) (22E772610a)

### LinearMouse

v0.9.0

### Describe the bug

Seems to be a regression of
https://github.com/linearmouse/linearmouse/issues/220

With the most recent update, the mouse and trackpad fight each other if I'm moving the mouse while trying to scroll on trackpad.

### To reproduce

scroll with a trackpad while moving a mouse

**Comment by lujjjh** [comment]
Thanks for your feedback!

The fix will be included in the upcoming beta release.

**Comment by lujjjh** [comment]
I've published [v0.9.1-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.1-beta.2).

It would be helpful if someone could test if this is compatible with the M2 internal trackpad, as its behavior differs from other internal trackpads.

**Comment by aonez** [comment]
> It would be helpful if someone could test if this is compatible with the M2 internal trackpad, as its behavior differs from other internal trackpads.

@lujjjh probably you've already tested it but works perfectly with and M2 trackpad + external mouse.

**Comment by lujjjh** [comment]
@aonez Thank you for testing it! It seems like I can close this issue now.
