### ISSUE TITLE
App focus problem in Mac

### ISSUE THREAD

**Issue by TaeryungLee** [linearmouse/linearmouse#464]
### OS

macOS 버전 12.1(빌드 21C52)

### LinearMouse

v0.9.0

### Describe the bug

When the focus is out from the app, then the scroll in out-focused app is not controlled by linear mouse.

### To reproduce

For example,

I disabled the scroll acceleration for every apps.

The case occurs in a situation if there are a safari window and a VSCODE window are opened and the focus (currently working window) is on a safari window.

Then, if I try to move the cursor to VSCODE window and scroll the VSCODE window without clicking it (moving the focus to VSCODE), then the scroll is accelerated (i.e. not controlled by linear mouse).

### Expected behavior

I expected the scroll is controlled by linear mouse in any time, and for any window.

**Comment by lujjjh** [comment]
Scroll events should always be handled by LinearMouse. However, if you have configured app-specific scrolling settings, LinearMouse will use the scrolling settings of the currently focused app. In your case, LinearMouse will use the scrolling settings that are configured for Safari.

If that is not the case, it would be helpful if you could share your configuration. You can find it by going to Config and selecting "Reveal in Finder".

Of course, it would be more intuitive for LinearMouse to use the settings configured for the app that the cursor is hovering over in this situation. I'm considering changing the behavior.
