### ISSUE TITLE
Scrolling Bug in Safari

### ISSUE THREAD

**Issue by micro18** [linearmouse/linearmouse#467]
### OS

macOS 13.3.1 (a) (Build 22E772610a)

### LinearMouse

v0.9.0

### Describe the bug

The scrolling does not work in Safari, works pretty much everywhere else.

### To reproduce

1. Launch Safari
2. Try scrolling

### Expected behavior

The page scrolls

### Anything else?

No

**Comment by lujjjh** [comment]
Thanks for your feedback!

I wasn't able to replicate this issue. Would you mind attaching your configuration file so that I can investigate further?

https://github.com/linearmouse/linearmouse/assets/3000535/5f998bc6-c85e-470c-aea2-b1413cf6410b
