### ISSUE TITLE
Some issues with Logitech GPW 2

### ISSUE THREAD

**Issue by TangBean** [linearmouse/linearmouse#475]
### OS

macOS 13.3.1 (a) (Build 22E772610a)

### LinearMouse

v0.9.1

### Describe the bug

1. Ctrl + scrolling not work, Cmd/Opt + scrolling is OK.
2. Buttons / Assign actions to mouse buttons can not record the side buttons of GPW 2.

But, these functions are working well with Logitech GPW 1, not sure if it's a problem only with GPW 2.

**Comment by lujjjh** [comment]
Thanks for your feedback!

Would you mind letting me know if you have Logi Options installed? I've heard from some other users that similar software can cause conflicts.

Also, can you confirm whether both GPW 1 and GPW 2 are using the same settings?

**Comment by TangBean** [comment]
Thanks for your reply!

Regarding the first question: I have installed G HUB, but I have tested the functions both with and without G HUB installed, and it didn't work in either case.

As for the second question: I am certain that GPW 1 and GPW 2 are using the same settings.

If you need any log files for debugging, pls feel free to ask for them!

**Comment by TangBean** [comment]
What confuses me the most is why the LinearMouse app works well with the GPW 1, but not with the GPW 2. I use the same laptop with different mouses. The GPW 1 is used at the office and the GPW 2 is used at home. Currently, the office experience is perfect! (I love the new function: Assign actions to mouse buttons). However, the home experience is not as good as the office T_T

**Comment by lujjjh** [comment]
我怀疑日志里没有有效的信息，不过还是可以提供一下。因为如果录制按键没有反应，说明按键没有传递到 LinearMouse。可能是被其他软件劫持了（显然 G HUB 已经被你排除），也可能是鼠标本身没有产生对应的事件。

我之前用过一款小米的鼠标，如果用 2.4GHz 接收器连接，侧键在 macOS 下无法使用，但是使用蓝牙连接就没问题，罗技鼠标还没有遇到类似的情况，或许你可以尝试一下 GPW 2 不同的连接方式有没有区别。

至于 control+滚动不工作，倒是更像是被其他软件劫持了，因为理论上跟 cmd/option+滚动没什么区别。
