### ISSUE TITLE
acceleration of scrolling can not be modified 

### ISSUE THREAD

**Issue by wxweguc54333** [linearmouse/linearmouse#476]
### OS

macOS 13.4

### LinearMouse

v0.9.1

### Describe the bug

The configuration of acceleration of scrolling can not be changed. When I change the acceleration to 1.5, it still keep 1.

### To reproduce

1. Open the linearmouse
2. Turn to the scrolling page
3. Change acceleration value to 1.5

### Expected behavior

Acceleration value can be changed to 1.5

**Comment by lujjjh** [comment]
Can you attach your configuration file? It's possible that you're experiencing the same issue as described in #457.
