### ISSUE TITLE
Side buttons don't work properly?

### ISSUE THREAD

**Issue by alexpalmakpop** [linearmouse/linearmouse#479]
### OS

macOS 13.4

### LinearMouse

0.9.1

### Describe the bug

Hi there,
I'm enjoying your wonderful app customizing my Mionix NAOS usb. Everything works perfectly except side buttons for left-right on browsers.
Let me explain better: buttons work, but for example, if I click on back button, it only goes for one back and if I click it again to go more back, it goes forward instead of going again back. 
I don't know how to let them work properly - tried also to customize it with "assign actions to mouse button" but nothing.
Am I doing something wrong?
Thanky you!

**Comment by lujjjh** [comment]
Thanks for your feedback!

Does this issue occur only in browsers? And can you please provide the logs after reproducing the problem?

**Comment by alexpalmakpop** [comment]
I think it's a general problem but I only use this feature in browsing mode - it's a bit annoying because for example - when I saw 3-4 youtube videos, if I click on side button to go back, he goes in the previous video and, if I wanna click it again to go in the first video I saw, he instead go forward.. and it's like a back and forth from the last page and the previous one. Trying to upload a log file

**Comment by alexpalmakpop** [comment]
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/11618579/LinearMouse.log)
Sorry for the delay - I uploaded the log here.

**Comment by lujjjh** [comment]
Thank you for sharing the log and I've reproduced this issue.

As far as I can tell, this issue seems to be specific to Opera. The side buttons are not being handled as expected and it is unclear whether this is an intended feature or a bug.

As a wordaround, I convert side buttons to swipe gestures in Opera (#483). In the upcoming beta version, enabling the universal back and forward function should address this issue.

**Comment by lujjjh** [comment]
Please upgrade to [v0.9.2-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.2-beta.1).

**Comment by alexpalmakpop** [comment]
Upgraded and now it works woderfully! 
Thank you so much!
