### ISSUE TITLE
Accessibility prompt always appear, can't launch properly

### ISSUE THREAD

**Issue by Damien-B** [linearmouse/linearmouse#482]
### OS

macOS 13.3.1 (22E261)

### LinearMouse

v0.9.1

### Describe the bug

I just downloaded the software, and the accessibility prompt always appear, even after adding accessibility permissions. This means I can't go pass that window and do anything with the software.

### To reproduce

On a macbookpro intel chip, with macOS 13.3.1 (22E261) installed
Try downloading from https://linearmouse.app and installing
The accessibility window request appear
Open the privacy security system settings > accessibility > allow linear mouse
Nothing happens with the linear mouse software\
Try restarting the software, the accessibility window appear again
Loop

### Expected behavior

The software should detect the permissions are granted and let the user use the app. It does not.

**Comment by ric03** [comment]
I had the same issue. After reseting the accessibility permission and granting the permission again, it did work.
