### ISSUE TITLE
Map mouse buttons to copying and pasting | 建议添加鼠标按钮功能：复制 粘贴

### ISSUE THREAD

**Issue by hanhan-phy** [linearmouse/linearmouse#484]
### OS

macOS 版本13.5（版号22G5027e）

### LinearMouse

v0.9.1

### Is your feature request related to a problem?

如标题

### Describe the solution you'd like

如标题

**Comment by lujjjh** [comment]
Thank you for the feedback! This request partially overlaps with issue #468 (which can be achieved by simulating <kbd>⌘ C</kbd> and <kbd>⌘ V</kbd>), but I will not close this issue temporarily as there may be further optimizations that can be made specifically for the copy and paste actions.

感谢反馈！这个需求与 #468 部分重叠（可以通过模拟 <kbd>⌘ C</kbd>、<kbd>⌘ V</kbd> 实现），不过考虑到可能可以针对复制、粘贴动作进一步优化，我暂时不关闭这个 issue。
