### ISSUE TITLE
Buttons configuration for custom apps

### ISSUE THREAD

**Issue by Densz** [linearmouse/linearmouse#494]
### OS

macOS 13.0 (Build 22A8380)

### LinearMouse

v0.9.1

### Describe the bug

I looks like there are duplicated entries for each buttons and it keeps growing.
![CleanShot 2023-06-09 at 11 37 56](https://github.com/linearmouse/linearmouse/assets/14071514/f60de8a3-b08b-4499-96f4-d1698d33b85b)

### To reproduce

1. LinearMouse Mouse Settings
2. Buttons
3. Select an App (like Google Chrome)
4. Add and remove shortcut

**Comment by lujjjh** [comment]
Thanks for your feedback!

I can reproduce this issue and will fix it soon.

**Comment by lujjjh** [comment]
Fixed in [v0.9.2-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.2-beta.2).
