### ISSUE TITLE
Extreme stuttering, quitting app fixed it

### ISSUE THREAD

**Issue by hyperknot** [linearmouse/linearmouse#502]
### OS

macOS 13.4 (Build 22F66)

### LinearMouse

v0.9.1

### Describe the bug

I noticed extreme stuttering, using my Macbook Pro's built in trackpad. It was happening in all applications, but most visible in Chrome.

I tried everything I could, and at one point I've quit LinearMouse from the menubar, and then the stuttering immediately got fixed.

After I restarted the app now it seems to be working fine, but I'm opening the bug report because there really was some serious stuttering.

In LinearMouse the Apple built-in device's settings were on the defaults, I've even clicked reset for both horizontal and vertical.

### To reproduce

No idea.

### Expected behavior

Working smoothly.

**Comment by lujjjh** [comment]
Thanks for your feedback.

Would you mind exporting the logs in the general settings when this issue occurs?

**Comment by hyperknot** [comment]
OK, I'll do that once it happens again.

**Comment by hyperknot** [comment]
It happened again, this time not extreme, just a bit of stuttering. I made some iPhone slo-mo videos, it's very visible on them.

I also made some logs, how can I best send it to you?

https://vimeo.com/840190805?share=copy
https://vimeo.com/840190877?share=copy

**Comment by lujjjh** [comment]
Thank you for the update.

> I also made some logs, how can I best send it to you?

You may upload the logs directly here or email them to [feedback@linearmouse.app](mailto:feedback@linearmouse.app). I'll check them out.

**Comment by hyperknot** [comment]
Here is one: https://www.dropbox.com/s/mfu4p5wymn89cjm/LinearMouse.log?dl=0

**Comment by lujjjh** [comment]
Thanks for sharing the logs.

Are you still using v0.9.1? It appears that the issue may have been caused by a memory leak in the event transformer, which has been fixed in the latest version, v0.9.2.

**Comment by hyperknot** [comment]
Yes, 0.9.1 I might try 0.9.2 then

**Comment by logkirk** [comment]
I'm also having what I think is the same issue on 0.9.2.

OS: macOS 13.4.1 (22F82)
linearmouse: 0.9.2
Issue: Stuttering when scrolling vertically and horizontally with the trackpad. Quitting and restarting linearmouse fixed the issue. I also noticed that the process's CPU usage seemed to drop after restarting, though I didn't check memory usage.

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12041361/LinearMouse.log)

**Comment by lujjjh** [comment]
@logkirk Could you please verify if this issue has been resolved in [v0.9.3-beta.4](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.3-beta.4)?

**Comment by kdrag0n** [comment]
I just started seeing this behavior recently on v0.9.3. For context, this is what it looks like from the perspective of app that uses the Accessibility API to record input:

https://github.com/linearmouse/linearmouse/assets/7930239/b990345b-172d-46c1-aeb7-026727315ff6

Some click events aren't reported, and others get a mouse-down event but no mouse-up for a while.

This was recorded with a mouse + Logi Options, but I've been using this combo for a few months with no issues, and the same thing is now happening with the builtin touchpad + keyboard.

Restarting LinearMouse fixes it temporarily but it starts to stutter again after a few minutes.

**Comment by lujjjh** [comment]
@kdrag0n, thank you for your feedback! It seems like this is different issue. Based on the logs you provided, it appears that the event tap was disabled multiple times due to timeouts. This is likely the cause of the issue you're experiencing in the screen recording.

Can you confirm that this issue does not exist in v0.9.2 and previous versions? Also, could you share your configuration (linearmouse.json)? I'll check if I can reproduce this issue using your configuration and Logi Options installed.
