### ISSUE TITLE
unable to record Logitech MX Master 3 `Gesture button`

### ISSUE THREAD

**Issue by EXHades** [linearmouse/linearmouse#504]
### OS

macOS 13.4 (22F66)

### LinearMouse

0.9.1

### Describe the bug

- can not record `Gesture button` button from `MX Master 3`
- default `MX Master 3` press the `Gesture button` will execute `cmd+tab`
- `Gesture button`：
<img width="599" alt="image" src="https://github.com/linearmouse/linearmouse/assets/22260242/5df319ab-a4e5-4d42-aaa1-bf2c80d1f6ee">

### To reproduce

1. uninstall Logitech `options puls` and `G HUB`
2. restart system
3. use `Buttons/Assign actions to mouse buttons` record
4. press the `Gesture button` record get `cmd`

<img width="850" alt="image" src="https://github.com/linearmouse/linearmouse/assets/22260242/784218b9-7d5c-43f7-8dbb-4f0a364d8c5f">

**Comment by EXHades** [comment]
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/11779401/LinearMouse.log)

**Comment by EXHades** [comment]
> [LinearMouse.log](https://github.com/linearmouse/linearmouse/files/11779401/LinearMouse.log)

复现过程中还发现，按下 `Gesture button` 获取为 `cmd` 时还会出现设置页面卡死现象，只能强制退出重新启动 LinearMouse 才能导出日志

**Comment by lujjjh** [comment]
Thank you for the detailed feedback!

There's a related issue (https://github.com/Hammerspoon/hammerspoon/issues/3373) I found that might be able to explain what's going on. According to [this article](https://scribe.rip/macbook-m1-and-mx-master-3-setting-buttons-without-logioptions-337790ba4cb3) performs the same function as the left command key.

I think it might be worth giving Karabiner-Elements a try and binding the left command on your Logitech MX Master 3, just like the article suggests. I'll consider how to approach this situation within LinearMouse and whether or not to implement this feature.

**Comment by EXHades** [comment]
thank，I'll try it.

**Comment by agubz** [comment]
I have been finding this problem with all mouse programs I'm downloading, including logitech options+, whenever I try to add a keyboard shortcut with CMD, it will only pull that up and never the next key. I'm losing my mind here, downloaded two other programs that I'm going to go try out now - this one isn't working for me.
