### ISSUE TITLE
"Repeat on hold" continues to execute the action repeatedly even when the button is released

### ISSUE THREAD

**Issue by WanliZhong** [linearmouse/linearmouse#506]
### OS

macOS 版本13.4（版号22F66）

### LinearMouse

v0.9.2

### Describe the bug
Set up two keys for switching space, I do not know how it triggered the switching function several times in a row, can not stop.

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/11796206/LinearMouse.log)

https://github.com/linearmouse/linearmouse/assets/49567307/61fe3f12-3b8c-4799-8940-e890a53e16a8

### To reproduce

I'm not sure.

**Comment by lujjjh** [comment]
Thanks for your feedback!

Did you enable "Repeat on hold" (按住时重复) when you press and hold the key? I can confirm that this bug occurs when switching between spaces with "Repeat on hold" turned on.

**Comment by WanliZhong** [comment]
Thanks! I do enable this option. Should I disabled it?

**Comment by lujjjh** [comment]
> Thanks! I do enable this option. Should I disabled it?

Yes, disabling the feature temporarily can serve as a workaround. I will address this issue and it will be resolved in the next release.

**Comment by lujjjh** [comment]
This issue has been fixed in [v0.9.3-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.3-beta.1).

Thanks for your feedback again!

**Comment by WanliZhong** [comment]
Thank you, your tool is good enough and I always recommend it to my friends.
