### ISSUE TITLE
Mission Control Space-Change control improvements

### ISSUE THREAD

**Issue by inclinated** [linearmouse/linearmouse#518]
### OS

macOS 13.4.1 (Build 22F82)

### LinearMouse

v0.9.2

### Is your feature request related to a problem?

I dislike the implementation of changing Mission Control spaces as requiring two separate key bindings for "Move Left A Space" and "Move Right A Space"

### Describe the solution you'd like

I would like an additional option to change spaces requiring only one mouse keybind that lets you drag left or right between Mission Control spaces, similar to  "Mac Mouse Fix" at macmousefix.org. 

### Describe alternatives you've considered

Current choice is great, no alternative required

### Additional context

This is just a suggestion and may not be in-line with your vision for your app and that's cool! Thanks for the snappy app :)

**Comment by lujjjh** [comment]
Thanks for your feedback.

You may want to subscribe to #397.
