### ISSUE TITLE
滚动的设置达不到想要的效果

### ISSUE THREAD

**Issue by liuzhcn** [linearmouse/linearmouse#540]
### OS

macOS 版本13.4.1（版号22F82）

### LinearMouse

v0.9.2

### Describe the solution you'd like

1. 改进滚动功能，达到和mos（一个开源软件）一样的滚动体验。目前这个还完全不行。
2. 可以单独关闭滚动或者指针的设置，因为我用mos的时候不喜欢这个软件的滚动设置形成冲突。

**Comment by lujjjh** [comment]
1. Duplicates of #44.
2. You can click on "Revert to system defaults" to undo the changes you made and return to the original system defaults. This will ensure that there are no conflicts with other applications.
