### ISSUE TITLE
Disable horizontal mouse scroll when holding shift

### ISSUE THREAD

**Issue by supa42** [linearmouse/linearmouse#544]
### OS

macOS 13.4.1 (c) (Build 22F770820d)

### LinearMouse

v0.9.2

### Is your feature request related to a problem?

When playing games on macOS, I cannot use the scroll wheel to cycle weapons when sprinting by holding shift, because shifting changes scrolling to horizontal.

### Describe the solution you'd like

I would love it if there was a way within LinearMouse to disable horizontal mouse scrolling when holding shift. I've just discovered a workaround by using the per-device settings for my mouse and setting the shift modifier key to 'change speed - 0.05' and this works pretty well as I don't notice the speed difference; It would still be cool in the future to just simply disable it though. 

### Additional context

Absolutely love the app by the way, thank you.

**Comment by lujjjh** [comment]
Thanks for your feedback.

An "Ignore Modifier" option will be added in the next release.
