### ISSUE TITLE
Keyboard shortcut for button mapping

### ISSUE THREAD

**Issue by LitteRabbit-37** [linearmouse/linearmouse#556]
### OS

macOS 13.5 (Build 22G74)

### LinearMouse

v0.9.3

### Describe the bug

For example, when I press "command" + "shift" + "-" with the 3 key on my mouse, it ignores the "-". Many keys are not taken into account for my commercial "+", "=", "1", "2". It seems that only the letters are correctly displayed. I was still able to edit the JSON file and add "-" myself, but there's no way of doing it for "+". The JSON file is saved, but the software resets the action, and I get a "default action" in the software. And yet, in the JSON file, I still have the "+" with the "keypress" option. No way of mapping the "+". What's more, in the JSON file, the headings "command" and "shift" don't seem to have any impact, whether it's "true" or "false". I have to map it myself by pressing the "commandRight" key, for example.

### To reproduce

Buttons > add > record a key > keyboard Shortcut > press "+" key > nothing happens

### Expected behavior

It should normally record correctly all keys, and the JSON file should work even if the record doesn't work properly.

### Anything else?

I have AZERTY keayboard, Keychron K2 Pro, LinearMouse Version 0.9.3, MacOS Ventura 13.5

**Comment by lujjjh** [comment]
Thank you for your feedback!

> For example, when I press "command" + "shift" + "-" with the 3 key on my mouse, it ignores the "-". Many keys are not taken into account for my commercial "+", "=", "1", "2".

I was able to reproduce that those keys not being able to record. I'll fix it in the next version.

> It seems that only the letters are correctly displayed. I was still able to edit the JSON file and add "-" myself, but there's no way of doing it for "+". 

You can try <kbd>⇧ ⌘ =</kbd> instead of <kbd>⇧ ⌘ +</kbd>. I have not added the numpad keys yet, including the individual <kbd>+</kbd> key, because numpad keys are not frequently used on Mac.

> What's more, in the JSON file, the headings "command" and "shift" don't seem to have any impact, whether it's "true" or "false". I have to map it myself by pressing the "commandRight" key, for example.

Could you explain it more?

**Comment by LitteRabbit-37** [comment]
> Thanks for your feedback!

I'd like to thank you for your work and your software, which has come in very handy!

> I was able to reproduce that those keys not being able to record. I'll fix it in the next version.

Nice, thank you !

> You can try ⇧ ⌘ = instead of ⇧ ⌘ +. I have not added the numpad keys yet, including the individual + key, because numpad keys are not frequently used on Mac.

I tried but to no avail. My aim was to be able to zoom out and in using the thumb buttons on the mouse. And when I do that, it's the "=" that's pressed and not the "+", despite the "shift" key being registered.

> Could you explain it further?

This applies to the "+" key in particular. I don't know if other keys are affected. When I want to assign the zoom to key 4 on my mouse via a keyboard shortcut "command" + "+". I tried to use the JSON file by writing this (software not open):
`{
      "buttons" : {
        "universalBackForward" : true,
        "mappings" : [
          {
            "action" : {
              "keyPress" : [
                "commandRight",
                "+"
              ]
            },
            "option" : false,
            "shift" : false,
            "button" : 4,
            "command" : false,
            "control" : false
          }
        ]
      }`
And when I save the JSON file and open (start up) the LinearMouse software, under the heading "Assign Action to mouse buttons" I see "Default action" for the 4 key on my mouse.
I then reopen my JSON file, so that it updates as displayed in the software. And to my surprise, I still have the same code, namely :
`{
      "buttons" : {
        "universalBackForward" : true,
        "mappings" : [
          {
            "action" : {
              "keyPress" : [
                "commandRight",
                "+"
              ]
            },
            "option" : false,
            "shift" : false,
            "button" : 4,
            "command" : false,
            "control" : false
          }
        ]
      }`
And not this code:
`{
      "buttons" : {
        "universalBackForward" : true,
        "mappings" : [
          {
            "option" : false,
            "shift" : false,
            "button" : 4,
            "command" : false,
            "control" : false
          }
        ]
      }`
I've tried other key combinations, but as soon as I add the "+", nothing works.

**Comment by LitteRabbit-37** [comment]
Also, I don't have numpad. it's a 75% keyboard.

**Comment by lujjjh** [comment]
Perhaps I didn't explain it clearly. Will `"keyPress" : ["shift", "command", "=" ]` work?

**Comment by lujjjh** [comment]
Many applications also recognize <kbd>⌘ =</kbd> as a shortcut for zooming in, so even though we typically use <kbd>⌘ =</kbd> to zoom in, we may not have realized it. So you could also specify `"keyPress" : ["command", "="]`.

**Comment by LitteRabbit-37** [comment]
In software, no. But via JSON, yes. But I want to zoom using `⌘ +`. But, if I use `⇧ ⌘ =` in JSON, it software it's correct, but `⇧ =` is not acting as `+`.

**Comment by LitteRabbit-37** [comment]
> Many applications also recognize ⌘ = as a shortcut for zooming in, so even though we typically use ⌘ = to zoom in, we may not have realized it. So you could also specify "keyPress" : ["command", "="].
You're right, with keyboard `⌘ =` works, but via LinearMouse, even with JSON set to these keys mapping, it doesn't work, it doesn't zoom in.
<img width="629" alt="Screenshot-2023-07-29-13 38 29" src="https://github.com/linearmouse/linearmouse/assets/133410979/9dff10b9-66ad-4531-86a5-2824e130ef7f">

**Comment by lujjjh** [comment]
Ah, I got it. It seems that the reason for this is the same as the one causing some keys to not be recorded. I'll investigate further. Thank you once again!

**Comment by lujjjh** [comment]
This issue has been fixed in [v0.9.4-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.4-beta.1).

**Comment by LitteRabbit-37** [comment]
So fast
