### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by zekx-z** [linearmouse/linearmouse#562]
### OS

macOS 版本12.6.6（版号21G646）

### LinearMouse

v0.9.3

### Describe the bug

0804更新后鼠标指针卡顿

**Comment by lujjjh** [comment]
感谢反馈。

是否有更详细的信息便于定位或者重现问题？比如在活动监视器中观察进程的 CPU 使用率是否异常。如果可以，请复现后在“通用”中导出日志，拖拽到回复框中上传。
