### ISSUE TITLE
蓝牙连接的鼠标不能识别侧键

### ISSUE THREAD

**Issue by fzzee** [linearmouse/linearmouse#563]
### OS

macOS 版本12.6.8（版号21G725）

### LinearMouse

v0.9.3

### Describe the bug

蓝牙连接的鼠标不能识别侧键，2.4G和有线连接识别正常

**Comment by lujjjh** [comment]
感谢反馈。遇到问题的鼠标型号是？是否安装了 Logitech Options 或者其他可能拦截侧键的 app？

**Comment by fzzee** [comment]
鼠标型号是狼蛛SC580，没有安装其他任何鼠标相关的软件，鼠标是三模的，2.4G模式和有线模式连接都可以识别到侧键，只有蓝牙模式识别不到；另外，同类软件 Mac Mouse Fix 也是识别不到蓝牙模式下的侧键，但是 SteerMouse 就可以识别到蓝牙模式连接的侧键

**Comment by lujjjh** [comment]
之前遇到过（好像是）小米双模鼠标有类似的问题，但是我记得当时测试 SteerMouse 也无法识别。

可以测试一下鼠标在不安装任何鼠标相关软件的时候，侧键的原生功能是否正常（比如在 Chrome 里是前进、后退，在 Safari 里可以点开链接）。

**Comment by fzzee** [comment]
蓝牙模式按键原生识别不到，安装了SteerMouse就能识别到了，他好像给安装了个驱动，希望大佬可以研究一下
<img width="679" alt="截屏2023-08-06 18 42 17" src="https://github.com/linearmouse/linearmouse/assets/26182676/83dda531-c151-45e3-a7bb-63e51d27c495">

**Comment by lujjjh** [comment]
看了你的截图，我估计 SteerMouse 是通过读 HID report 实现的，红色部分就是当前按下的按键（可能是多个按键），不过还需要考虑在什么条件下采用这种降级策略。

**Comment by lujjjh** [comment]
请更新到 [v0.9.4-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.4-beta.2)。
