### ISSUE TITLE
manually adjusting pointer speed doesnt work

### ISSUE THREAD

**Issue by Meannekes** [linearmouse/linearmouse#565]
### OS

macOS Sonoma Beta4 (23A5301h)

### LinearMouse

0.9.3

### Describe the bug

i set acceleration to 0 and want to adjust the mouse speed but it doenst change.
it is the same speed with for example with pointer speed set to 0,069 and 1,0.

**Comment by lujjjh** [comment]
Thanks for your feedback.

Could you reproduce this issue and export the logs from the General settings?

**Comment by Meannekes** [comment]
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12298938/LinearMouse.log)

this is with my Logitech MX Master. same behaviour. Acceleration Set to 0 and Speed doesnt do anything.
![Xnip2023-08-09_08-21-29](https://github.com/linearmouse/linearmouse/assets/63404696/6e5b6d21-db65-4869-a7f9-c49d99c4ec51)

**Comment by lujjjh** [comment]
I can confirm that the mouse pointer speed is not working properly on macOS Sonoma, while the trackpad pointer speed is functioning correctly. I will look into this more later. Thank you!

**Comment by Meannekes** [comment]
Weird, Trackpad Pointer Speed is also not wokring for me. Macbook internal Trackpad and the external Magic Trackpad

**Comment by lujjjh** [comment]
If you are an M2 user, then yes, you can refer to issue #270 for more information.

**Comment by Meannekes** [comment]
i have an M2 MB Air yes, but my Trackpads get listet
![Xnip2023-08-09_12-32-06](https://github.com/linearmouse/linearmouse/assets/63404696/79f339f3-519d-4b3e-a5d2-a63566dd8938)

**Comment by lujjjh** [comment]
Yes, I have received multiple reports indicating that the pointer speed does not function properly for M2 internal trackpads. For example, #279 and #492. This issue remains reresolved.

**Comment by lujjjh** [comment]
I've figured out why the pointer speed wasn't functioning properly. I disabled the pointer acceleration in the System Settings. Kindly verify if you have done the same.

<img width="755" alt="image" src="https://github.com/linearmouse/linearmouse/assets/3000535/732de7d3-6290-4e38-9e2e-df7e67c67cfe">

I turned it on again and the pointer speed now works.

**Comment by Meannekes** [comment]
after enabling Pointer acceleration in the System Settings i can configure the external Magic Trackpad and my Logitech with LinearMouse.
