### ISSUE TITLE
Option not use Universal back and forth with a list of apps, or to pass through the original back and forth buttons as well

### ISSUE THREAD

**Issue by ThunderFD** [linearmouse/linearmouse#57]
Hey there!

Awesome that this exists, I was frustrated with my external mouse when I first got my mac a few months ago and this is very very nice software with all the features you really need :D 
On to my feature request and why one would want/need that:

### **Issue:**
I'm using the current version from Homebrew

Back and forth works great now with LinearMouse everywhere so far other than one place:
Remote-ing into my Windows PC via Parsec.

Parsec used to pass on the hardware side button clicks directly to my windows pc (but my mac obviously didn't know what to do with them), but as LinearMouse now converts those to swipe gestures nothing happens anymore (on my remote windows machine)

### **Fix / Feature Request:**
This could be fixed by Parsec by implementing swipes on their mac client to send side button clicks, or by LinearMouse by:
1. not deleting the hardware side button click event when converting to swipes
or
2. adding a blacklisting (and whitelisting) feature per application for all sorts of features

not sure if 1. could lead to problems if other software actually handles the mouse side buttons as well as swipe gestures - either triggering the same action twice, or triggering two different actions.
But this could be the much easier fix to my problem (if it's possible) and similar ones with other apps that actually handle the side buttons in macos (I don't know any though, maybe games?).

option 2. could be useful for other cases as well, like setting mouse acceleration per application (again, could be useful for games).

**Comment by lujjjh** [comment]
Hi @ThunderFD,

Thank you for opening this issue!

I've noticed this issue in VS Code as well. Option 1 could result in the problem you say, and this is why LinearMouse deletes the raw click events.

I'm considering maintaining an application blacklist for this feature because a) it seems most apps handle swipe events and just a few handle only side button clicks, b) we can embed the list so most users would find it just works without any configuration, and c) application-specific settings could be difficult to implement for things like mouse acceleration.

But I'm not very certain for a). Only VS Code, virtualization applications, and remote control applications occur to me in my use cases.

**Comment by ThunderFD** [comment]
> Thank you for opening this issue!

Sure thing!

> I've noticed this issue in VS Code as well.

Oh wow, you're right - VS Code also has this issue

> I'm considering maintaining an application blacklist for this feature

Yeah this would be an option too, and it would also be pretty easy for users familiar with GitHub to create issues or pull requests to add another Application to that list/config file, helping all other users of Linearmouse in the process :)


So yeah, I'd be happy if something like that was implemented!

**Comment by lujjjh** [comment]
Would you provide the `CFBundleIdentifier` of Parsec?

A simple way is to run

```sh
osascript -e 'id of app "Parsec"'
```

in Terminal.app.

**Comment by lujjjh** [comment]
I've added Parsec into ignore list. You may try the version [here](https://github.com/linearmouse/linearmouse/actions/runs/1765363695).

**Comment by ThunderFD** [comment]
> Would you provide the CFBundleIdentifier of Parsec? 

Sorry it was in the middle of the night for me

> I've added Parsec into ignore list. You may try the version here.

That was fast!
I've tried it out and it works perfectly in Parsec and VS Code! thank you!
