### ISSUE TITLE
Just got the update for 0.9.4-beta.2 and it broke disabling acceleration.

### ISSUE THREAD

**Issue by mapleroyal** [linearmouse/linearmouse#572]
### OS

macOS 14.0 latest public beta

### LinearMouse

 0.9.4-beta.2

### Describe the bug

Just got the update for 0.9.4-beta.2 and it broke disabling acceleration. Restarting the app hasn't helped. Disabling and re-enabling disabling of acceleration hasn't fixed it.

### To reproduce

Go from whatever was the previous linearmouse beta to this version.

### Expected behavior

Disabling of acceleration would continue to work as it always has.

### Anything else?

Wondering how to revert to the previous version.

**Comment by lujjjh** [comment]
Thanks for your feedback!

This issue will be fixed soon in the upcoming beta release. Alternatively, you may also downgrade to [the previous version](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.4-beta.1) manually if you prefer.

**Comment by lujjjh** [comment]
[v0.9.4-beta.3](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.4-beta.3) has been released.
