### ISSUE TITLE
Override Logi Options + for scroll key modifiers

### ISSUE THREAD

**Issue by carlodrift** [linearmouse/linearmouse#574]
### OS

macOS 13.5 (22G74)

### LinearMouse

0.9.3

I have LinearMouse configured this way:

```
"scrolling" : {
        "speed" : 0,
        "acceleration" : 1,
        "modifiers" : {
          "vertical" : {
            "option" : {
              "type" : "preventDefault"
            },
            "shift" : {
              "type" : "ignore"
            },
            "control" : {
              "type" : "preventDefault"
            },
            "command" : {
              "type" : "preventDefault"
            }
          }
        }
```

I've done this so that 'shift + scroll' scrolls vertically as if shift wasn't pressed. I need this for some applications and games.

However, as soon as I launch Logi Options+, it no longer works and 'shift + scroll' scrolls horizontally.
I've unchecked the option that avoids conflicts with other applications' events.
There is no option in Logi Options+ to disable this behavior.

Would it be possible to create an option to voluntarily override Logi Options+ on this and allow 'shift + scroll' to scroll vertically?

**Comment by lujjjh** [comment]
When Logi Options+ is running, do other scrolling options, such as scrolling speed, still work properly? I think Logi Options+ intercepts the scrolling events and doesn't pass them to LinearMouse. In this situation, I don't think LinearMouse can do anything.

**Comment by carlodrift** [comment]
LinearMouse settings for scroll speed and direction work well despite Logi Options+.

**Comment by lujjjh** [comment]
Could you please reproduce it and export the logs? I will look into it later.

**Comment by carlodrift** [comment]
[Log with Logi Options open, modifier no longer works](https://github.com/linearmouse/linearmouse/files/12840563/LinearMouse.2.log)
[Log with Logi Options closed, modifier works correctly](https://github.com/linearmouse/linearmouse/files/12840564/LinearMouse.log)
