### ISSUE TITLE
Possible to implement smooth scrolling? 

### ISSUE THREAD

**Issue by rightsaidfred99** [linearmouse/linearmouse#576]
### OS

13

### LinearMouse

Latest beta

### Is your feature request related to a problem?

Currently even with settings of

Scrolling acceleration set to .01
Scrolling speed set to 0

I'm getting warp speed scrolling. If i move it beyond this I'm getting light speed scrolling. 
MOS is the perfect app for smooth scrolling, it's like butter, but that app misses many things that LinearMouse does so well. 

I think it would be great to have an option to turn on smooth scrolling. 

### Describe the solution you'd like

Have an option to turn on buttery smooth scrolling like the native mac mouse does

### Describe alternatives you've considered

MOS does it well. 

### Additional context

Using a Logitech M650

**Comment by lujjjh** [comment]
Thanks for your suggestion.

Duplicates of #44.
