### ISSUE TITLE
Safari smooth scrolls with trackpad but is very choppy when scrolling with an external mouse

### ISSUE THREAD

**Issue by stjepangolemac** [linearmouse/linearmouse#588]
### OS

macOS 13.4.1 (c) (Build 22F770820d)

### LinearMouse

v0.9.3

### Is your feature request related to a problem?

Other browsers like Chrome and Firefox scroll smoothly with a mouse but not Safari. This is a widely known issue and 3rd party solutions are usually recommended.

Solutions I came across:
- https://www.smoothscroll.net/mac/
- https://github.com/Caldis/Mos/blob/master/README.enUS.md

The problem is that I don't want to use anything other than LinearMouse. This app is already perfect and this is just a nitpick.

### Describe the solution you'd like

Figure out a way to enable smooth scrolling for Safari, the same as other browsers. Other solutions do this so it might just be a matter of figuring out what they do.

### Describe alternatives you've considered

- https://www.smoothscroll.net/mac/
- https://github.com/Caldis/Mos/blob/master/README.enUS.md

**Comment by lujjjh** [comment]
Thanks for your suggestion.

Duplicates of #44, #540, #576.

I haven't started implementing it yet, mainly because there are already several apps out there doing the same thing, as you mentioned. However, since this is a frequently requested feature, I would consider to bump up its priority.

**Comment by smvueno** [comment]
Also voting for this 😍 Having this as an option in the settings would really make Linear Mouse ALL MIGHTY! 😎👌
I tried mos but it's also affecting the scroll on my tablet and I cant have that, makes the tablet feel unresponsive and slugish.

**Comment by stjepangolemac** [comment]
Anti-closure bump!

**Comment by C1ares** [comment]
I'd love to see this as well. mos isn't maintained well and it already shows
