### ISSUE TITLE
鼠标加速度的问题

### ISSUE THREAD

**Issue by aioob** [linearmouse/linearmouse#591]
### OS

macOS 版本14.0（版号23A5328b）

### LinearMouse

v0.8.0

### Is your feature request related to a problem?

请问在这个软件中对应windows的加速度应该设置成多少

### Describe the solution you'd like

无

### Describe alternatives you've considered

无

### Additional context

无

**Comment by lujjjh** [comment]
有多个相关的讨论：#121、#383。macOS 的加速度曲线与 Windows 的不同，所以目前无法只通过调整加速度的值，使体验与 Windows 下完全相同。如果只是想要类似的体验，建议是把加速度设置在 0~0.1 之间（我个人使用 0.07），然后调整速度到合适的值。
