### ISSUE TITLE
Allow -1 input into the acceleration

### ISSUE THREAD

**Issue by sealvessel** [linearmouse/linearmouse#592]
### OS

macos ventura

### LinearMouse

latest

### Is your feature request related to a problem?

I can't make it -1. It should be allowed because that is basically no acceleration, but witohut the sluggishness of the zero option. It basically makes one:one movement with the mouse to the display. 

### Describe the solution you'd like

Allow the boolean value of -1. 

### Describe alternatives you've considered

Just allow inputting -1 to make it so that it writes this into the defaults menu, defaults write -g com.apple.mouse.scaling -1. 
I don't need this app mostly because I can just input that. I use this app mainly for trackpads as well as scrolling.

**Comment by lujjjh** [comment]
You could just toggle "Disable pointer acceleration" on.

**Comment by sealvessel** [comment]
It decreases the DPI in half compared to -1. 
If I have 1600 DPI, then it would be halved. With -1 acceleration, it remains the same as 7/11 windows settings that is, with the hiDPI mode 1600DPI. 
So -1 or a one:one mapping function for the linear acceleration is needed. I don't know which slider value is exactly 2.

**Comment by lujjjh** [comment]
It's weird because the "Disable pointer acceleration" option actually just sets the acceleration to -1 [behind the scenes in Ventura](https://github.com/linearmouse/linearmouse/discussions/201#discussioncomment-3147900).

**Comment by sealvessel** [comment]
Can this please be reopened, the option in ventura sets it to -1 while this app is different and modifies it with an integer value.

**Comment by lujjjh** [comment]
@sealvessel Sure, we can reopen this issue. Could you please provide a more details? In Ventura, enabling the "Disable pointer acceleration" option in LinearMouse is the same as setting the pointer acceleration to -1. When you say "compared to -1," do you mean comparing the "Disable pointer acceleration" option in LinearMouse with using the command `defaults write -g com.apple.mouse.scaling -1` or something?
