### ISSUE TITLE
Mouse 4 and 5 constantly pressed when moving mouse

### ISSUE THREAD

**Issue by CralJuicer** [linearmouse/linearmouse#593]
### OS

13.2.1 (22D68)

### LinearMouse

newest version

### Describe the bug

When i plug in my mouse and move the sensor, it uses the inputs both as movements but also constantly presses Mouse 4 and mouse 5. It only presses the buttons whenever i move the mouse itself. It is a bug that started happening today, and will only got away when i quit the software.

### To reproduce

i Open linearMouse, and plug my mouse in
I move my cursor, and its starts to press mouse 4 and 5 constantly as long as i move the mouse

**Comment by lujjjh** [comment]
Thanks for your feedback! I'm guessing this is relavent with #570. Could you export the logs in General settings? And, what's your mouse model?

**Comment by sosafe-joern-piontek** [comment]
Same issue with a lenovo sm50l24506. For what it's worth, I usually have a Steelseries Kana V2 plugged in and haven't encountered that issue in the past. I did update LinearMouse yesterday and think I would've caught it if it happened with the Steelseries mouse (which legitimately has Mouse 4 and 5, whereas the Lenovo does not).

**Comment by sosafe-joern-piontek** [comment]
Log: https://pastebin.com/HyiviPeZ

**Comment by lujjjh** [comment]
Please upgrade to [v0.9.5-beta.1](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.5-beta.1) and see if this bug is resolved.

**Comment by sosafe-joern-piontek** [comment]
Looks like it has fixed things for me :) Thank you so much, LinearMouse has been crucial in my transition from Windows to MacOS.
