### ISSUE TITLE
custom Acceleration curve 

### ISSUE THREAD

**Issue by Jomyy** [linearmouse/linearmouse#61]
So you can see a curve and you can just edit the curve for prefect customization 
just a thought tho

like imagine a 2d wavetable synth were you can edit the curve directly

**Comment by lujjjh** [comment]
Like [CursorSense](https://plentycom.jp/en/cursorsense/index.html)?

<img src="https://user-images.githubusercontent.com/3000535/152213653-ceb14a4d-7897-4900-9a27-83bf1df3c40b.png" width="334" />

I'm not sure if the curve graph would help. For me, I have to move the cursor to see if it fits me. :)
