### ISSUE TITLE
Mouse acceleration only for touchpad

### ISSUE THREAD

**Issue by Tai-Png** [linearmouse/linearmouse#613]
### OS

macOS 13.5.2 (Build 22G91)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

I have to manually turn off mouse acceleration when im using my touchpad instead of the mouse. I wonder if it's possible to have mouse acceleration on for touchpad and off for mouse.

### Describe the solution you'd like

Mouse acceleration is on for touchpad but off for the mouse

**Comment by lujjjh** [comment]
Absolutely! LinearMouse is designed to provide support for per-device settings. This means that you have the flexibility to customize the settings for your touchpad and mouse separately.

Here's the device indicator, representing the current device you are configuring for:

<img width="528" alt="image" src="https://github.com/linearmouse/linearmouse/assets/3000535/50d3a3ce-8629-4ebe-ad74-c3792924c373">
