### ISSUE TITLE
Wrong keyboard shortcut

### ISSUE THREAD

**Issue by rox97** [linearmouse/linearmouse#614]
### OS

macOS 14.0

### LinearMouse

v0.1.9-beta.1

### Describe the bug

I wanted to map button 3 and 4 as <kbd>Control</kbd> + <kbd>leftArrow</kbd> and <kbd>Control</kbd> + <kbd>rightArrow</kbd>, but instead it's mapped as <kbd>Command</kbd> + <kbd>leftArrow</kbd> and <kbd>Command</kbd> + <kbd>rightArrow</kbd>

**Comment by lujjjh** [comment]
Apologies for the delayed response. However, I haven't reproduced this problem.

Just to clarify, are you referring to whether LinearMouse has incorrectly recorded the keyboard shortcuts, or if it has recorded the correct shortcuts but is simulating the wrong ones?

By any chance, have you swapped the <kbd>control</kbd> and <kbd>command</kbd> keys in the System Settings or through any other keyboard utilities?

**Comment by rox97** [comment]
LinearMouse ha correctly recorded the keyboard shortcuts, but is simulating the wrong ones. I recorded <kbd>Control</kbd> + <kbd>leftArrow</kbd> and <kbd>Control</kbd> + <kbd>rightArrow</kbd> but is simulating <kbd>Command</kbd> + <kbd>leftArrow</kbd> and <kbd>Command</kbd> + <kbd>rightArrow</kbd>. I didn't change the default setup of my keyboard, and if i use the shortcuts from the keyboard, they works just right

**Comment by lujjjh** [comment]
Could you please reproduce this issue and upload the logs exported in General settings here?

BTW, is your keyboard layout QWERTY?

**Comment by rox97** [comment]
Sure. i have an italian qwerty
[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12817461/LinearMouse.log)

**Comment by lujjjh** [comment]
Thank you! I can confirm this issue and will fix it soon.

In the meantime, you may select "Move Left a Space" and "Move Right a Space" actions if they fulfill your requirements.

**Comment by rox97** [comment]
Thank you! i'm so dumb i didn't notice there were the option without a keyboard shortcut but i'm glad i could found a bug that can be fixed for someone else. Thank for your work!
