### ISSUE TITLE
LinearMouse breaks tracking speed on mouse (not on trackpad).

### ISSUE THREAD

**Issue by mapleroyal** [linearmouse/linearmouse#616]
### OS

macOS 13.5.2 (Build 22G91)

### LinearMouse

v0.9.5

### Describe the bug

With linearmouse open, the tracking speed is the slow default speed. As soon as I quit linearmouse, the tracking speed returns to the speed I have it set at in the system settings. Reopening linearmouse causes the default speed to return (note: it doesn't actually change the system setting in the system settings GUI, but it does have the same effect as if the system setting was set to something much slower).

**Comment by mapleroyal** [comment]
This bug is still happening on the new macOS 14.0.

**Comment by lujjjh** [comment]
Hi @mapleroyal, thanks for your feedback!

Do you expect LinearMouse to not alter the tracking speed (i.e. pointer acceleration) of your mouse? Have you changed the pointer settings of your mouse in LinearMouse? You may try clicking "Revert to system defaults" in the Pointer settings.

**Comment by mapleroyal** [comment]
Yes, I guess I expected it to fix the acceleration without interfering with the system's tracking speed. I now see that you can set the tracking speed in the linearmouse app. Apologies for this oversight, but thank you for your clarification.

**Comment by lujjjh** [comment]
Yeah, it can get pretty confusing that the tracking speed on macOS is actually referring to the pointer acceleration (before macOS Sonoma offers the option to disable it).

I'm closing this issue. Please feel free to reopen it if you have any further questions.
