### ISSUE TITLE
Change Spaces by holding middle button and draging

### ISSUE THREAD

**Issue by MSamiulHasnat** [linearmouse/linearmouse#632]
### OS

macOS 14.0 (Build 23A344)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

Sometimes it is inconvenient to exchange between different spaces by the trackpad while holding the regular mouse. So this problem can be fixed with this feature. 

### Describe the solution you'd like

The solution is simple. Hold the middle button or scroll wheel whatever you call and drag it left and right. Just like Mac Mouse Fix. But that app crashes too much and doesn't work on every machine.

**Comment by Triskae** [comment]
It would be really nice to have this 😍

**Comment by Shavcat** [comment]
Yes! It would be nice if we could assign 2 buttons to 1 action. Just like in Mac Mouse FIx

**Comment by MSamiulHasnat** [comment]
Are you going to add this feature?
