### ISSUE TITLE
can't use option + scroll down and option + scroll up simultaneously 

### ISSUE THREAD

**Issue by singhdan2002** [linearmouse/linearmouse#633]
### OS

macOS 14.0 (Build 23A344)

### LinearMouse

v0.9.5

### Describe the bug

I mapped option + scroll up to increase volume and
option + scroll down to decrease volume

if i increase vol with the mapping i can't simply scroll down to decrease volume
i tried to even release the option key and try again, but it simply doesn't work

**Comment by lujjjh** [comment]
I couldn't reproduce this issue. Would you mind reproducing it and then exporting the logs from General settings?

https://github.com/linearmouse/linearmouse/assets/3000535/8b95354c-57be-4c7a-970f-6d88eda84e6d

**Comment by singhdan2002** [comment]
somehow, it works now, however it's kinda laggy, is there a way to make it more responsive?

here's the log you asked for, hope this helps

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/13110347/LinearMouse.log)
