### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by VedantPatil1** [linearmouse/linearmouse#641]
### OS

macOS 14.0 (Build 23A344)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

May I am just new to this app, but currently I have to use your app to configure my mouse and then use an app like smoothscroll to achieve a smooth scrolling experience.

### Describe the solution you'd like

I would like for you to add this feature to this app itself in the scroll config section. It would at least for me make it complete solution.

### Describe alternatives you've considered

I have considered using BetterMouse which is paid software. Although it is not that expensive, I can achieve the same effect by using two free (LinearMouse & SmoothScroll or MOS) apps instead of this paid app. 

### Additional context

I am new to both MacOs and LinearMouse. You can revert to me if you would like any assistance from my side.

**Comment by Wulgaren** [comment]
this would be amazing!

**Comment by patrulea** [comment]
#44

**Comment by jhult** [comment]
@lujjjh, should we close this as a dupe of #44?

**Comment by lujjjh** [comment]
> @lujjjh, should we close this as a dupe of #44?

Yes, let's keep track of this feature request in #44.
