### ISSUE TITLE
reverse scorlling doesn't working in vlc media player

### ISSUE THREAD

**Issue by RajveerDebnath27** [linearmouse/linearmouse#653]
### OS

macOS 14.1.1 (Build 23B81)

### LinearMouse

v0.9.5

### Describe the bug

I am facing a problem with the VLC player's sound control. it does not support the reverse scrolling when I try to increase or decrease the volume.
when I scroll the wheel down it increases the volume and when I scroll up it decreases the volume.
<img width="884" alt="Screenshot 2023-11-28 at 1 58 02 PM" src="https://github.com/linearmouse/linearmouse/assets/96521809/6fd2e29b-bdb8-44c9-aacd-354232f279a8">

here I provided the screenshot of the linear mouse settings.

### Expected behavior

I was expecting that if I scrolled up, the volume should be increased, and if I scrolled down, the volume should be decreased.

### Anything else?

let me know if it was a bug or not.

**Comment by lujjjh** [comment]
> I was expecting that if I scrolled up, the volume should be increased, and if I scrolled down, the volume should be decreased.

I remember that this is the default behavior of VLC, so you might need to turn off reverse scrolling for VLC.
