### ISSUE TITLE
Disabling accessibility permissions can hard-lock a machine

### ISSUE THREAD

**Issue by bast0006** [linearmouse/linearmouse#667]
### OS

14.2 (23C64)

### LinearMouse

v0.9.5

### Describe the bug

Disabling the accessibility permission while the app is in use hard-locks the machine by preventing all clicks and keypresses from all connected or to be connected input devices.

### To reproduce

1. Disable mouse acceleration
2. open the settings window for accessibility
3. un-toggle the permission for linearmouse

### Expected behavior

The app to deactivate itself, raise an error, or something that doesn't involve intercepting all attempts to undo what you just did by accident

**Comment by bast0006** [comment]
I attempted to use the "reset to defaults" key combination but it didn't appear to do anything. Perhaps consider adding a similar one that copletely disables it?

**Comment by lujjjh** [comment]
Thanks for your feedback.

This is a known issue. There are no notifications when the accessibility permissions have been revoked, and proactive permission checks are also ineffective. In other words, the applications are unable to detect when their permissions have been revoked. However, I've just thought about a potential workaround. Will try it later.
