### ISSUE TITLE
使用Command+鼠标滚轮进行手势缩放问题

### ISSUE THREAD

**Issue by itarze** [linearmouse/linearmouse#677]
### OS

macOS 版本14.2.1（版号23C71）

### LinearMouse

v0.9.6-beta.2

### Describe the bug

WPS 中使用Command+鼠标滚轮进行手势缩放时，松开Command按键后依然触发，关闭LinearMouse后就不触发了  
![image](https://github.com/linearmouse/linearmouse/assets/89234190/6e5772ce-ef2c-4625-a83c-f6ff24a16980)

### Expected behavior

按下Command修饰键后配合鼠标滚轮进行缩放，所开Command修饰键后恢复默认动作

**Comment by itarze** [comment]
[v0.9.6-beta.3](https://github.com/linearmouse/linearmouse/releases/tag/v0.9.6-beta.3) 也有此问题

**Comment by lujjjh** [comment]
感谢反馈，但是我没能重现这个问题：

https://github.com/linearmouse/linearmouse/assets/3000535/d64e1bdc-947c-487a-80d5-bae5602fda0c

能否提供复现时的日志，或者更详细的复现步骤？

**Comment by hotsno** [comment]
I also have this same issue. I'm not able to test the latest commit currently as I don't have Xcode installed yet, but I may be able to do that later.

This is happening to me when trying to zoom on a website (GitHub) using Arc browser.

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/14235309/LinearMouse.log)

**Comment by lujjjh** [comment]
I've just released [v0.10.0-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.10.0-beta.2). Could you check if it resolves this issue?

我刚刚发布了 [v0.10.0-beta.2](https://github.com/linearmouse/linearmouse/releases/tag/v0.10.0-beta.2)，能否测试一下有没有解决这个问题？

**Comment by hotsno** [comment]
> This is happening to me when trying to zoom on any website (e.g. GitHub) using Arc browser.

It seems like it happens everywhere for me, not just Arc browser. I tried zooming on an image in Preview app as well, and the same thing happens.

**Comment by lujjjh** [comment]
@hotsno Thanks for sharing the logs. Could you also attach your configuration file? It looks like the "Keychron Q2" is being mistakenly identified as a mouse.

**Comment by hotsno** [comment]
No problem!

[linearmouse.json](https://github.com/linearmouse/linearmouse/files/14236204/linearmouse.json)

**Comment by lujjjh** [comment]
@hotsno Please kindly try [this build](https://github.com/linearmouse/linearmouse/actions/runs/7869199803?pr=693). I hope this issue is fixed.

**Comment by hotsno** [comment]
It's fixed, thanks :)
