### ISSUE TITLE
Debounce support for mouse scroll wheel

### ISSUE THREAD

**Issue by TylerWhittaker** [linearmouse/linearmouse#679]
### OS

macOS 14.2.1

### LinearMouse

0.9.5

### Is your feature request related to a problem?

I am using a Razer Basilisk v3 mouse.  Razer inexplicably decided that the mouse wheel left/right should repeatedly send "mouse wheel left" / "mouse wheel right" events extremely rapidly while the button is held down.  

For example, I like to assign mouse scroll right to keyboard shortcut "ctrl+tab" for my browser (and mouse scroll left to ctrl+shift+tab).  This allows me to switch tabs using mouse wheel left/right.  However, even my fastest click on the mouse generates at least 10 ctrl+tab events, so I jump 10 tabs to the right.  My intention is to generate only one ctrl+tab event, so I move on tab to the right.  

I have verified this unusual mouse behavior via several apps in macOS and Linux.  The behavior is also documented by Razer.

### Describe the solution you'd like

I believe that debounce support for the mouse scroll wheel (along with tweaking the debounce time) would solve this issue.  

### Describe alternatives you've considered

I'm currently using BetterTouchTool to handle mouse scroll wheel to ctrl+[shift]+tab, which supports ignoring repeated inputs.

I attempted to use Razer's Synapse 2 software to configure the mouse, but it is broken on recent macOS versions.  I then installed Razer Synapse 3 in a Windows VM to reconfigure the mouse.  This was not successful -- despite the fact that the software can rebind mouse buttons and store this changed profile directly on the mouse (so it would work on macOS), it is unable to rebind scroll left/right to disable rapidly sending events and save this configuration on the mouse.

**Comment by aaomidi** [comment]
Should this be reopened @lujjjh
