### ISSUE TITLE
Setting pointer speed on M3 Max Internal Trackpad has no effect

### ISSUE THREAD

**Issue by ViRb3** [linearmouse/linearmouse#681]
### OS

macOS 14.2.1

### LinearMouse

v0.9.5

### Describe the bug

Setting pointer speed on M3 Max Internal Trackpad has no effect. Worked just fine on my M1 Max before, and also still works on my external mouse.

**Comment by ViRb3** [comment]
Closing as duplicate of #270.

**Comment by ViRb3** [comment]
In fact, reopening as not exactly the same - the product name and vendor are present, however, changing pointer speed does not work:
![Screenshot 2024-01-31 at 20 52 56](https://github.com/linearmouse/linearmouse/assets/2650170/42159a7b-650d-4bf7-9648-c835b7dd9bf3)

Looking at https://plentycom.jp/en/cursorsense/download.php, this doesn't look good:
> System Requirements
Mouse, built-in trackpads (except Macs released after 2022), Magic Mouse and Magic Trackpad are supported.

**Comment by DRRoca** [comment]
+1
