### ISSUE TITLE
Cmd + scroll to zoom dosent work on certain apps

### ISSUE THREAD

**Issue by simonchrom** [linearmouse/linearmouse#684]
### OS

macOS 14.2 (assemblage 23C5055b)

### LinearMouse

v0.9.5

### Describe the bug

i've set up my parameters so as to zoom when I hold cmd and scroll, but on microsoft Word, it doesn't work, when I hold cmd and scroll down (to unzoom, it just write and Buch of "-" 

### Anything else?

https://github.com/linearmouse/linearmouse/assets/59965412/59ab0a76-5c0f-4cb5-967e-6d109f936ea6

**Comment by lujjjh** [comment]
Please take a look at https://github.com/linearmouse/linearmouse/issues/586#issuecomment-1701277673 and see if it helps.
