### ISSUE TITLE
0.10 laggy drag click

### ISSUE THREAD

**Issue by sealvessel** [linearmouse/linearmouse#688]
### OS

sonoma 14.1

### LinearMouse

0.10 beta

### Describe the bug

Laggy drag click

### To reproduce

1. Drag click a window

### Expected behavior

Smooth

**Comment by lujjjh** [comment]
Could you please provide more details? It would helpful if you could confirm whether this issue also occurred in previous versions. If possible, it would be appreciated if you could export and upload the logs after reproducing the issue.

**Comment by venoman9867** [comment]
I use linear mouse in the game league of legends, you can try to install it and click quickly, the cursor freezes and does not move, but by disabling the program everything becomes normal

**Comment by brianysoong** [comment]
+1 with the same issue here, new to version 0.10.0-beta.1, and not occurring with previous versions. When using a wired mouse (Logitech G303), and initiating a click-to-drag to highlight or move something, there is an extreme lag in the first 5-10 seconds of moving (the cursor freezes in place) and then afterwards the cursor teleports to the desired position. If you keep the mouse button held down, then the lag goes away, but as soon as you let go + click-to-drag again, the lag returns. 

I've tried random things like turning on/off "Disable Pointer Acceleration" and other settings, nothing seems to fix the issue besides quitting linearmouse. 

Strangely, this doesn't happen at all with my wireless mouse (Logitech MX Master 3S).

**Comment by lujjjh** [comment]
@brianysoong Thank you for your response! I'm unable to reproduce the issue on my end. I've attempted to revert 2 suspicious commits respectively. It would be great if you could test both builds and see if the issue persists:

1. https://github.com/linearmouse/linearmouse/actions/runs/7911994659
2. https://github.com/linearmouse/linearmouse/actions/runs/7912047834

**Comment by brianysoong** [comment]
@lujjjh The first build didn't fix the issue, but the second build fixed the issue. 

This issue also occurs with my wireless Logitech G305. Perhaps related to mice with high polling rates, since my mouse with a low polling rate didn't have the issue?

**Comment by lujjjh** [comment]
I have refined the implementation of per-display settings. Please verify if the issue has been fixed in [v0.10.0-beta.3](https://github.com/linearmouse/linearmouse/releases/tag/v0.10.0-beta.3).
