### ISSUE TITLE
Switch mouse buttons

### ISSUE THREAD

**Issue by Jegwebb** [linearmouse/linearmouse#691]
### OS

macOS 14.2.1 (Build 23C71)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

I'm al lefty using a left handed mouse.  These left handed mice have the left and right buttons reversed which is a problem as a lot of left handed users still use the buttons the standard way around.  Would it be possible to have a toggle to reverse the left and right buttons?

### Describe the solution you'd like

A reverse left and right click option.

**Comment by lujjjh** [comment]
Thanks for your feedback!

You might consider updating LinearMouse to the latest beta version as it now includes this feature.
