### ISSUE TITLE
OSX 14.3.1 does not work

### ISSUE THREAD

**Issue by maximilianotaverna** [linearmouse/linearmouse#692]
### OS

osx 14.3.1

### LinearMouse

v0.10.0 beta1

### Describe the bug

followed all instructions .
rebooted.
not working

### To reproduce

installed
executed

### Expected behavior

smooth scroll

**Comment by falkben** [comment]
I noticed that with 14.3.1 there's now an option in "Mouse" system settings under "Advanced" that allows you to turn off acceleration.

![image](https://github.com/linearmouse/linearmouse/assets/653031/2946fbbf-e486-4c21-bee8-aaa6b8947e1b)

**Comment by lujjjh** [comment]
I've updated to macOS 14.3.1 and everything appears to be functioning smoothly on my end. Could you give me a bit more information on what isn't working? BTW, LinearMouse currently doesn’t offer a smooth scrolling feature.
