### ISSUE TITLE
Infinite scroll up and down

### ISSUE THREAD

**Issue by mmx2004** [linearmouse/linearmouse#702]
### OS

14.3.1 M2

### LinearMouse

0.9.5

### Is your feature request related to a problem?

I would like to assign the side buttons to "Go to top" and "Go to bottom" actions. I think this is pretty useful.

### Describe the solution you'd like

Currently, I can assign the maximum numbers of line scrolls which is 10 to a side button. I suggest to increase this to 20 and then after 20 there will be one more level with the name of "Infinite" (or something like that) so I can choose that instead of a number. That is going to scroll straight to top or bottom.

### Additional context

Thanks for your nice software. It helps a lot. Keep up the good work.

**Comment by lujjjh** [comment]
Thanks for suggestions!

Perhaps mapping the side buttons to the keyboard shortcuts for <kbd>fn</kbd><kbd>left</kbd> and <kbd>fn</kbd><kbd>right</kbd> will do the trick (in most scenes).

However, be aware that there can be issues when trying to recoding the <kbd>fn</kbd> key; it might help to hold down the <kbd>fn</kbd> key prior to pressing the "Click to record" button. 'll also take a look at what might be causing the problem and work on fixing it.

<img width="962" alt="" src="https://github.com/linearmouse/linearmouse/assets/3000535/470711bc-a1d1-4676-a09f-84d81229931f">
