### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Roytol** [linearmouse/linearmouse#704]
### OS

macOS 14.3.1 (Build 23D60)

### LinearMouse

v0.9.5

### Describe the solution you'd like

wish it enable remove from the menu bar.
a feature to hold the back/ fourth button and the scrolling will be horizontally

**Comment by jacobarcarola** [comment]
Do you mean that you would like to be able to horizontally scroll using the side buttons on your mouse?

**Comment by Roytol** [comment]
No, I mean that if you press and hold one of the side buttons and then
scrolling regularly, it will scroll horizontally. :)
(Logo Options app have these feature)
