### ISSUE TITLE
Enable/disable function

### ISSUE THREAD

**Issue by TigerCat-hu** [linearmouse/linearmouse#705]
### OS

macOS 14.3.1 verzió (23D60 build)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

I would like to disable or enable the Scrolling, Pointer and Buttons functions. I use the SmoothScroll app, I don't want it, both control the same thing. Can it be solved? Thanks! 😊

PS: This app is very good, I love it, thanks for your work! I have a Xiaomi MI mouse, in BT mode this is the only app that works with the side buttons. Yes! 👍🙏

### Describe the solution you'd like

Don't control the scrolling. That's all.

**Comment by lujjjh** [comment]
Thanks for you feedback. Can you provide more specific details about the issue you're encountering with LinearMouse when using SmoothScroll? LinearMouse is designed not to interfere with scrolling functions if you leave the default scrolling settings unchanged.

**Comment by TigerCat-hu** [comment]
I found the switch. Looks good now... Is that okay? Is that enough? Thank you very much!

<img width="619" alt="image" src="https://github.com/linearmouse/linearmouse/assets/33827733/675c098a-0588-4f51-84fa-105aa1f313d1">
