### ISSUE TITLE
Support for more buttons

### ISSUE THREAD

**Issue by RobaloAmigo** [linearmouse/linearmouse#711]
### OS

macOS Wersja 14.3.1 (kompilacja 23D60)

### LinearMouse

v0.9.5

### Describe the solution you'd like

I have a Logitech G604 mouse with two rows of side buttons with 3 buttons each row. Only the 2 of 6 buttons (named #3 and #4 in LinearMouse) are registered by LinearMouse. Is it possible to implement support for registering the rest of the side buttons?

**Comment by clayih** [comment]
I'd love to see this as well!
