### ISSUE TITLE
Logitech option gestures feature

### ISSUE THREAD

**Issue by namtv95** [linearmouse/linearmouse#715]
### OS

macOS 14.4 (Build 23E214)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I'd like to have a gestures like logitech options+, that when i hold a mouse button (mouse 4, 5) and move to left or right so it can switch between desktop (same gestures swipe left or right with three fingers)
Thank you for all your hard work.

**Comment by lujjjh** [comment]
Seems duplicated with #397.
