### ISSUE TITLE
功能建议：支持App中鼠标动作映射键盘按键

### ISSUE THREAD

**Issue by 36bian** [linearmouse/linearmouse#727]
### OS

macOS 版本11.6.5（版号20G527）

### LinearMouse

v0.9.5

### Describe the solution you'd like

我使用ibooks看书时，发现鼠标滚轮不能控制翻页，只能用键盘的左右，很难受。
linearmouse的配置里有“分配鼠标按钮的动作”功能，但是没有键盘的选项。

所以，希望增加一个“自定义某个app 把鼠标动作转换成键盘动作”的功能，感谢！❤️

**Comment by lujjjh** [comment]
你好，动作选择“键盘快捷键…”，然后录制对应的按键即可。

**Comment by 36bian** [comment]
> 你好，动作选择“键盘快捷键…”，然后录制对应的按键即可。

真的可以，感谢！
