### ISSUE TITLE
App build information

### ISSUE THREAD

**Issue by rakleed** [linearmouse/linearmouse#73]
Could you add information on how to build the app myself in the README?

**Comment by lujjjh** [comment]
There's no magic:

1. Open project with Xcode.
2. Choose your Team in ‘Signing & Capabilities’ in target ‘LinearMouse’.
3. Click Run / Build.

Please let me know if you encounter any problems during the build process.

**Comment by rakleed** [comment]
When I try to build the app, I get two errors:
- `There are no accounts registered with Xcode. Add your developer account to Xcode`
- `No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "C5******J7" with a private key was found.`

I added my AppleID account in `Xcode › Preferences › Accounts`, issued a certificate and restarted Xcode, but it did not help. And I also don't want to pay for [Apple Developer Program](https://developer.apple.com/programs/) $99, because I want to build the project only for myself.

**Comment by lujjjh** [comment]
No, you don't need to join in the Apple Developer Program.

Choose the right signing certificate and try again:

<img width="1125" alt="" src="https://user-images.githubusercontent.com/3000535/153028363-83006a55-9373-43fa-b3c0-d8a48f757734.png">

**Comment by rakleed** [comment]
Yes, it worked. Thanks! Maybe this information should be added to the README? Since I did not find the solution you described when googling my errors.

**Comment by lujjjh** [comment]
Code signing can now be configured [by running `make configure`](https://github.com/linearmouse/linearmouse/blob/main/BUILD.md).
