### ISSUE TITLE
该工具会导致IDEA窗口无法点击

### ISSUE THREAD

**Issue by songlongkuan** [linearmouse/linearmouse#740]
### OS

macOs 13.1

### LinearMouse

v0.7.5

### Describe the bug

我使用了两个鼠标，罗技G502、逻辑M590 ，两个鼠标使用linearmouse 配置鼠标按键，均会导致jetbrains idea开发工具的窗口不可点击，idea窗口点哪儿都没反应，其他的软件正常，基本每天都会出现，重装macos系统 重装idea都还会出现，后来卸载了linearmouse 更换为其他的鼠标按键配置工具后不再出现该问题，因此认为是linearmouse的问题

**Comment by lujjjh** [comment]
感谢反馈。由于描述得比较模糊，我无法重现这个问题。如果能提供具体的重现步骤或者 LinearMouse 配置文件，或许可以更好地帮助复现这个问题。
