### ISSUE TITLE
Automatically get different poimter speed on Safari

### ISSUE THREAD

**Issue by YohanJins** [linearmouse/linearmouse#748]
### OS

macOS 13.6.7 (Build 22G720)

### LinearMouse

v0.9.5

### Describe the bug

This happens whlile using Magic Trackpad(External).
When the pointer selects Safari on Mac, the pointer speed dcreases automatically.
On the other apps, the setting works exactly modified by user.

**Comment by lujjjh** [comment]
Did you accidentally configure a different pointer speed for Safari in LinearMouse?

**Comment by YohanJins** [comment]
No, I don’t think so. A far as I remember I didn’t do anything on Safari
independently.
All I did was connecting a Magic Trackpad and modified pointer speed. And
the setting is for ‘All apps’ of course.
One thing weird I see is, when I hit ‘All apps’ button only Safari is
showing it’s ‘Configured’ while I didn’t do anything with it though…
So I selected Safari and the pointer setting is working globally now lol
