### ISSUE TITLE
New LinearMouse update messed up my Mac trackpad 

### ISSUE THREAD

**Issue by cfd323** [linearmouse/linearmouse#760]
### OS

macOS 14.5 (Build 23F79)

### LinearMouse

v0.10.0

### Describe the bug

After installing new LM update, my track pad operates opposite of the way it used to; if I click with 1 finger, it responds as if I used 2 fingers. And if I use 2 fingers, it responds as if I clicked with 1 finger. The settings are the same as they were before installing the update. It's basically acting like it the mouse buttons were reversed. I checked the mouse settings and they are not reversed.

### To reproduce

Install LM and then the trackpad works like the buttons are opposite

### Expected behavior

I would like the trackpad to work correctly. It worked fine with LM installed, until I did the latest update.

**Comment by lujjjh** [comment]
Hey @cfd323, thanks for feedback!

Could you upload your configuration file?

**Comment by cfd323** [comment]
Sorry, new to Macbook/Mac OS. How do i do that?

**Comment by lujjjh** [comment]
No worries! You can find the configuration file by:
1. Click the LinearMouse icon on the menu bar.
2. Click Config -> Reveal in Finder

<img width="453" alt="Screenshot 2024-07-05 at 00 42 27" src="https://github.com/linearmouse/linearmouse/assets/3000535/82658924-c9fc-4d63-a6ab-2a99613ef449">

Also, please check if the "Switch primary and secondary buttons" option is enabled by mistake for trackpad:

<img width="962" alt="image" src="https://github.com/linearmouse/linearmouse/assets/3000535/bcbef1ff-32e8-4e71-bd92-f9f4b4e46ad0">
