### ISSUE TITLE
cmd+wheel not work in Pycharm

### ISSUE THREAD

**Issue by leavesullic** [linearmouse/linearmouse#765]
### OS

14.5 sonama

### LinearMouse

newest

### Describe the bug

choose cmd for scaling in linearmouse leads to  cmd + wheel not work in Pycharm for font size change.

### To reproduce

 if you choose cmd for scaling in linearmouse, many scenes will work perfectly like chrome, firefox.
But in Pycharm, cmd+wheel will not work for changing font size

**Comment by lujjjh** [comment]
Zoom simulates keyboard shortcuts under the hood. Pinch zoom should work as it simulates pinch gestures.

Another solution is to map cmd+wheel to the font size zooming keyboard shortcuts in PyCharm, which are shift+control+, and shift+control+. .

<img width="962" src="https://github.com/linearmouse/linearmouse/assets/3000535/81bdea87-ce72-4a5f-9823-0142ccfaf097">
