### ISSUE TITLE
Normal scrolling is not happening

### ISSUE THREAD

**Issue by YashJhanwar08** [linearmouse/linearmouse#773]
### OS

macOS 14.5 (Build 23F79)

### LinearMouse

v0.10.0

### Describe the bug

when i use a wired mouse it works properly when i disable reverse scrolling but whwn i connect a usb mouse it is not working properly

**Comment by jhult** [comment]
I just upgraded to Sequoia 15.0 (24A335) and have the same problem. My USB mouse scroll direction does not change no matter the "Vertical reverse scrolling" setting.
