### ISSUE TITLE
Pointer speed setting doesn't work macOS 15 public beta

### ISSUE THREAD

**Issue by ronaldland** [linearmouse/linearmouse#776]
### OS

macOS 15.0 (Build 24A5289h)

### LinearMouse

v0.10.0

### Describe the bug

Pointer > Pointer speed setting doesn't work macOS 15 public beta

### To reproduce

MacBook Pro 14 M1 Pro, using internal trackpad the pointer speed setting doesn't work. Have not tested external mice. Pointer acceleration does work.

### Expected behavior

The setting pointer speed to work again

**Comment by pawelkontek** [comment]
Having the same issue.

**Comment by Meieryang** [comment]
Me too, the internal trackpad is not working as excepted. but external mice works well.  My device is Macbook air, apple silicon M1 ,2020. macOS 15.1 beta

**Comment by Meieryang** [comment]
Here's the solution temporary. set Pointer acceleration 's value to 0.1，pointer speed to 0.21. then the pointer will not moving so slow.

**Comment by ronaldland** [comment]
Not stale, issue still not fixed.

**Comment by kurtistowery** [comment]
Problem is not fixed.

**Comment by igorbabko** [comment]
The problem is still there. Can this issue be reopened?
