### ISSUE TITLE
.config folder permission

### ISSUE THREAD

**Issue by MatGJB** [linearmouse/linearmouse#780]
### OS

macOS 14.5 (Build 23F79)

### LinearMouse

v0.10.0

### Describe the bug

Failed to save the configuration: You don’t have permission to save the file “linearmouse” in the folder “.config”

Can't use app, every time I get this message. how do I solve it?

**Comment by lujjjh** [comment]
Sorry for the late reply.

Please refer to https://github.com/linearmouse/linearmouse/issues/230#issuecomment-1207143043.
