### ISSUE TITLE
What is the default tracking speed without any changes?

### ISSUE THREAD

**Issue by skareel** [linearmouse/linearmouse#782]
### OS

macOS 14.6 (Build 23G80)

### LinearMouse

v0.10.0

### Describe the bug

The previous version of linearmouse didn't have tracking speed as far as I remember. You would go into pointer and hit "disable pointer acceleration" and that was it. Now there is a field to change your pointer speed but what is the default value where nothing changes about your mouse tracking so it is 1:1? I use logitech ghub to control my pointer speed and I only want linearmouse to disable acceleration and not affect the tracking at all.

<img width="903" alt="image" src="https://github.com/user-attachments/assets/b911b76b-f4b2-434f-ace3-8c278e456120">

### Expected behavior

1:1 tracking for my mouse and then the cursor speed would be controlled by logitech ghub

**Comment by BK1031** [comment]
When i set acceleration to 0 and speed to 0.35 i find it feels pretty close.
