### ISSUE TITLE
Inverted Scrolling Does Not Work with Magic Mouse

### ISSUE THREAD

**Issue by jtylerhartley** [linearmouse/linearmouse#79]
The checkbox for inverted scrolling does not work to invert the scrolling of my magic mouse.

**Comment by lujjjh** [comment]
Magic Mouse, like Trackpad, generates continuous wheel events. It's difficult to tell them apart.

I've implemented an experimental mouse detector and you can download the pre-release [here](https://github.com/linearmouse/linearmouse/actions/runs/1832846295) to see if it works.

Please make sure to turn on ‘Enable experimental mouse detector’.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/3000535/153697699-b16a25e6-5326-4870-b322-44667154566f.png">

**Comment by jtylerhartley** [comment]
Yes, this works! Thank you!
