### ISSUE TITLE
Mouse and trackpad acceleration doesn't work in macOS Sequoia

### ISSUE THREAD

**Issue by RansonTham42** [linearmouse/linearmouse#790]
### OS

macOS 15.0 (Build 24A5331b)

### LinearMouse

v0.10.0

### Describe the bug

Acceleration and speed settings in LinearMouse do not affect the behavior of the cursor. I'm using the trackpad. It worked in macOS Sonoma

**Comment by snoolord** [comment]
@RansonTham42 also seeing the same issue. would love for this to be reopened and updated
