### ISSUE TITLE
Universal Back and Forward Allowlist (or DenyList)

### ISSUE THREAD

**Issue by marlonchalegre** [linearmouse/linearmouse#793]
### OS

MacOS

### Is your feature request related to a problem?

Yes, Universal Back and Forward does not work for every app.

### Describe the solution you'd like

I'd like to have a option to AllowLIst or DenyList the apps that supports this feature. 

Nowadays, only apps listed in this [fixed variable](https://github.com/linearmouse/linearmouse/blob/385ecd890390830da3750d6501f53d6c4fca8c1c/LinearMouse/EventTransformer/UniversalBackForwardTransformer.swift#L11) are supported and any changes or new software need a code change.

A new UI to insert the AllowList to be used in [shouldHandleEvent](https://github.com/linearmouse/linearmouse/blob/385ecd890390830da3750d6501f53d6c4fca8c1c/LinearMouse/EventTransformer/UniversalBackForwardTransformer.swift#L33)

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
