### ISSUE TITLE
Ability to enable debounce for extra buttons

### ISSUE THREAD

**Issue by TakaiSaisei** [linearmouse/linearmouse#799]
### OS

macOS 14.6.1

### LinearMouse

0.10.0

### Is your feature request related to a problem?

In my case, the extra clicks are produced by one of the side buttons

### Describe the solution you'd like

It would be great to be able to enable the feature not only for the three main buttons, but for any other buttons as well

**Comment by hansira14** [comment]
up, same issue here :)) it would be nice to set the debounce for mouse sidebuttons as well
