### ISSUE TITLE
经常从笔记本休眠中恢复后所有配置项都恢复成默认了

### ISSUE THREAD

**Issue by lianginx** [linearmouse/linearmouse#800]
### OS

macOS 版本15.0（版号24A5298h）

### LinearMouse

v0.10.0

### Describe the bug

基本上每天都会出现这个问题

### To reproduce

电脑长时间不用，比如晚上下班合盖休眠，第二天启动并解锁后，就发现软件的所有配置项都恢复成刚安装时的样子

**Comment by lujjjh** [comment]
看起来症状类似 #764，可以观察一下设备名称后是否出现了随机乱码？

**Comment by lianginx** [comment]
> 看起来症状类似 #764，可以观察一下设备名称后是否出现了随机乱码？

我发现出现这个问题的原因了，我使用了 Karabiner-Elements，这个软件里面也有输入设备管理。

就是这个软件的原因导致每次从睡眠中唤醒之后，鼠标都被识别成了新设备，所以设置被重置了。

然后我在它的设备管理里关掉了一些不需要使用设备后就正常了，再也没有出现过这个情况。

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/04ef33c5-735f-4fb3-bbc9-00d60582e384">
