### ISSUE TITLE
Clicking Bug

### ISSUE THREAD

**Issue by Lemon-Tech365** [linearmouse/linearmouse#810]
### OS

macOS 15.0 (Build 24A335)

### LinearMouse

v0.10.0

### Describe the bug

On outlook.com, it's treating my left click as if I'm holding it down. 

### Expected behavior

It should register as a simple left click.

**Comment by hoefiger** [comment]
I cannot confirm this issue. Left-clicking works as expected in Microsoft Outlook (ARM-native).
