### ISSUE TITLE
Can't recognize Logitech Lift middle button

### ISSUE THREAD

**Issue by 0ptimista** [linearmouse/linearmouse#812]
### OS

Sonoma 14.7

### LinearMouse

v0.10.0

### Describe the bug

linearmouse can recognize model correctly
![CleanShot 2024-09-25 at 17 42 28@2x](https://github.com/user-attachments/assets/016053ad-f9ee-49a2-a8e5-bf02ee22e245)

But when recording button to customize a action. It doesn't recognize the middle button ( little button located under the scroll wheel)

![CleanShot 2024-09-25 at 17 47 52@2x](https://github.com/user-attachments/assets/248a6388-8ff8-4176-a735-147c5e6af733)

**Comment by kulas115** [comment]
Same here. It would be super useful to have this working 🙏🏼
