### ISSUE TITLE
add keyboard modifer key support for "Assign actions for mouse buttons"

### ISSUE THREAD

**Issue by eret9616** [linearmouse/linearmouse#826]
### Describe the solution you'd like

I hope that when holding down keyboard keys, ‘Assign actions to mouse buttons’ can have different functions and add support for keyboard keys and modifier keys.
<img width="626" alt="image" src="https://github.com/user-attachments/assets/dabd6a82-4a78-42ec-a655-8e79ecda489d">

**Comment by lujjjh** [comment]
<img width="259" alt="image" src="https://github.com/user-attachments/assets/921e575e-0832-48f5-8ba5-cc7f8f376bd8" />

Yeah, it does support modifier keys. Just hold the modifier keys you want when recording.
