### ISSUE TITLE
[Feature Request] restore default settings on exit

### ISSUE THREAD

**Issue by mxrlkn** [linearmouse/linearmouse#84]
When quitting LinearMouse, the default MacOS mouse settings aren't restored. I have to go into settings -> mouse and set the tracking speed to get the default speed and acceleration back.

This would be useful when only using LinearMouse for some apps, like games for example.

**Comment by lujjjh** [comment]
Thank you for your feedback!

You may try [this build](https://github.com/linearmouse/linearmouse/actions/runs/1850808215) and see if it fixes this issue.

**Comment by mxrlkn** [comment]
It works perfectly!

Thank you 🎉
