### ISSUE TITLE
Reverse scrolling not working after sleep or replug

### ISSUE THREAD

**Issue by collinkreutzer** [linearmouse/linearmouse#89]
Since 0.5.0 or 0.5.1 (don't know exactly, upgraded from 0.4.3 to 0.5.1 directly), mouse scrolling isn't reversed after waking from sleep. I have to manually disable and re-enable reversed scrolling in order to apply the setting again. This can be reproduced by unplugging and replugging the mouse too. Scrolling is then back to normal until I disable and re-enable reverse scrolling again.

**Comment by jankware** [comment]
I'm also having this issue. It also occurs after using the media control keys on my external keyboard to pause or unpause video, but does not occur when using the MacBook media control keys.

**Comment by lujjjh** [comment]
This is a regression introduced by supporting Magic Mouse. Would you please try [this build](https://github.com/linearmouse/linearmouse/actions/runs/1862439481)?
