### ISSUE TITLE
3 finger swipe to swap between desktops reverses constantly with new update

### ISSUE THREAD

**Issue by SpunZTV** [linearmouse/linearmouse#90]
With new update when I use the 3 finger swipe to switch between desktops the direction seems to keep going back and forth between natural and un natural seemingly at random whenever I open new apps / go full screen on apps. Regular scrolling up and down on mouse and track pad seem to be fine. Was working fine before update.

**Comment by SpunZTV** [comment]
Currently disabled the scroll reverser in linear mouse and using the "scroll reverser" app, currently working as a bandaid. The acceleration and mouse sens settings still working

**Comment by lujjjh** [comment]
This is a regression introduced by supporting Magic Mouse. Would you please try [this build](https://github.com/linearmouse/linearmouse/actions/runs/1862439481)?
